polypoly-eu/polyPod

features/facebookImport/src/components/errorPopup/errorPopup.css, features/facebookImport/src/components/errorPopup/errorPopup.jsx, features/facebookImport/src/context/importer-context.jsx, features/facebookImport/src/facebookImporter.jsx, features/facebookImport/src/model/storage.js, ios/PolyPodApp/PodApi/PolyOut/FS/PolyOut+FS.swift
I left the actual importers and analyses alone, since their error
handling feeds directly into the report. Since we don't have named error
types coming from the backend, we'd still have to include the message in
those to really be able to debug problems, however.
The global error popup is a bit ugly at this point, but I guess it's a
start.
=> PROD4POD-787 - Add error handling for importing/reading

features/facebookImport/src/facebookImporter.jsx, features/facebookImport/src/i18n.js, features/facebookImport/src/locales/de/report.json, features/facebookImport/src/locales/en/report.json, features/facebookImport/src/views/report/details.jsx, features/facebookImport/src/views/report/report.css, features/facebookImport/src/views/report/report.jsx
Still a bit different from the designs:
1. I combined the initial dialog and the second screen into one, to save
time for now.
2. I stuck to the old colours and didn't bother _too_ much with making
things look like in the design.
But the new content and flow is there. We will likely still have to
change those strings however, based on the record now not really being
about "unrecognized data" anymore.
=> PROD4POD-779 - Adjust report flow

features/facebookImport/src/model/analyses/off-facebook-events-analysis.js
There could be exports where there are no "PURCHASE" events.
=> Allow purchases  count to be zero

features/facebookImport/src/components/loading/loading.css, features/facebookImport/src/components/loading/loading.jsx, features/facebookImport/src/context/importer-context.jsx, features/facebookImport/src/locales/de/common.json, features/facebookImport/src/locales/de/explore.json, features/facebookImport/src/locales/de/overview.json, features/facebookImport/src/locales/en/common.json, features/facebookImport/src/locales/en/explore.json, features/facebookImport/src/locales/en/overview.json, features/facebookImport/src/views/explore/explore.jsx, features/facebookImport/src/views/import/import.css, features/facebookImport/src/views/import/import.jsx, features/facebookImport/src/views/overview/overview.jsx
Still a basic version - I'd use the same on _import_ and _overview_ if this seems like a decent approach.
**Update:** Now I've included a loading screen for the `overview` screen as well, and an overlay for `import`. That should do it for a very first version.
=> PROD4POD-809 - Add loading screen to explore view

core/utils/silly-i18n/README.md, core/utils/silly-i18n/package-lock.json, core/utils/silly-i18n/package.json
This upgrades a number of modules, eliminating deprecations [seen here, for instance](https://github.com/polypoly-eu/polyPod/runs/3654927222?check_suite_focus=true) as well as high severity vulnerabilities like [this one](https://www.npmjs.com/package/cypress).
It has done so mainly through the upgrade of the dependencies for the two testing frameworks used, `cypress` and `jest`
Also eliminates an unused dependency.
=> [Fix] silly-i18n maintenance

android/app/src/main/kotlin/coop/polypoly/polypod/polyOut/PolyOut.kt
3 things here:
1. Fix issue with only messages being parsed. It was because the feature expected all file names to start with `polypod://`
2. Add caching for `stat` and `readdir` - this helps with performance on huge files
3. Do not run `readFile` on UI thread - for performance reasons.
=> Fix issues on Android

features/facebookImport/src/views/overview/overview.css, features/facebookImport/src/views/report/details.css, features/facebookImport/src/views/report/report.css
Following the instructions in the Jira ticket, I have removed the scroll in all the sub-sections (or "report-cards"). However, I kept the horizontal scroll only for the tables. 
Some of these sub-sections include a table. I have tried the CSS property `word-break: break-all` (as it is done in the lists of files), but the tables didn't look good in this way. In order to show all the content, I added a horizontal scroll in these tables (only the table, not the whole "report-card"). 
Please let me know if you prefer to remove all the scrolling or if it's ok in this way.
=> PROD4POD-831/Fix scroll in Report details screen

features/facebookImport/package-lock.json, features/facebookImport/package.json
* Vulnerability fixed via `npm audit fix`
* `jest`now run tests, so no need for the flag
* This has been also upgraded to latest version, in order to avoid the `tmpl` vulnerability warning by dependabot.
=> [Fix] Fix moderate severity vulnerability and other upgrades

android/app/src/main/kotlin/coop/polypoly/polypod/polyNav/PolyNav.kt, features/facebookImport/src/components/importExplanationExpandable/importExplanationExpandable.jsx
This runs the import in a coroutine. But because the import function finishes before the import is actually done we do not yet know the final size of the import. So this also removes the size from the UI.
=> Fix Android black screen when importing

features/bundle/index.js
Mainly trying to address [this](https://github.com/polypoly-eu/polyPod/security/code-scanning/1?query=ref%3Arefs%2Fheads%2Fmain)
This mainly follows advice from [the advisory itself](https://codeql.github.com/codeql-query-help/javascript/js-shell-command-injection-from-environment/), however it does not really work, since it does not "find" any file. I'm not really sure if it's a bug, or a USB (user-side bug). So if you've got some advice here, I'd really appreciate it.
[Asked in StackOverflow](https://stackoverflow.com/questions/69358497/problems-with-using-globbing-together-with-execfilesync)
=> [Fix] Shell command built from env

features/example/package-lock.json, features/example/package.json
To be honest, I intended to eliminate `fetch-spec` from here, but that's not possible, since podjs depends on it. So it eventually became a maintenance PR.
=> [Task] Maintenance example feature

ios/.gitignore, ios/Makefile, ios/exportOptions.plist
One step closer to the sun! This command allows me to publish a release to the App Store from my local machine without too much hassle:
`./build.js clean && ./build.js && cd ios && make archive && make upload`
OK, there's a bit of hassle in the command itself :D But still, it's way better than all the clicking around in Xcode I currently have to do.
_Why can't we just do that via GitHub actions_ I hear you ask? Well, the problem is that we would need to get the **credentials** there. That looks like a lot of hassle to me, but also "just work". It's the final missing piece now.
=> Automate App Store upload

features/facebookImport/src/model/storage.js, features/facebookImport/src/views/overview/overview.jsx
Two big async issues that caused this:
1. handleRemoveFile was not awaited before leaving the overview (view)
2. Storage.removeFile resolved before triggering the change listener (I
suspect, didn't go to any lengths to find the _exact_ problem in that
function, but that's the main semantic difference I can see with my
changes.)
=> Fix race condition for new imports

features/facebookImport/src/model/analyses/about-pictures-data-analysis.js, features/facebookImport/src/model/analysis.js
This adds analysis that is triggered when the number of pictures is greater or equal to a threshold. The current threshold is 3. For now we count all pictures in the folder `photos_and_videos` with the extension png, jpg, jpeg or gif.
=> Add basic analysis triggered when there are pictures present in the export

features/polyExplorer/src/screens/companyDetails/companyDetails.jsx
I understand what are the issues, there's realy not a incredibly big risk, but unsanitized input might have its very own problems. This was also a simple fix and addresses [this](https://github.com/polypoly-eu/polyPod/security/code-scanning/6?query=ref%3Arefs%2Fheads%2Fmain), so why not.
=> Addressing critical vulnerability

features/facebookImport/src/model/analyses/ministories/post-reactions-types-analysis.js, features/facebookImport/src/model/analyses/utils/post-reactions-utils.js, features/facebookImport/src/model/analysis.js, features/facebookImport/src/model/entities/facebook-account.js, features/facebookImport/src/model/importer.js, features/facebookImport/src/model/importers/direct-key-data-importer.js, features/facebookImport/src/model/importers/post-reactions-importer.js, features/facebookImport/test/datasets/post-reactions-data.js, features/facebookImport/test/importers/post-reactions-importer.test.js, features/facebookImport/test/ministory/post-reactions-types-analysis.test.js, features/facebookImport/test/utils/data-importing.js
This imports reaction data to posts:
- only imports the type and the timestamp
- extends DirectKeyDataImporter with a hook for transforming data
- adds tests for the importer
- groups reactions by types
- adds a simple ministory that can be expanded
=> Import reactions

build/index.js, build/index.test.js, build/package-lock.json, build/package.json
This will allow us to do a manual partial rebuild when working on core
components quite a bit easier.
I also couldn't resist to finally introduce some tests for the build
logic. They are arguably not incredibly elegant, written against the
current state in the repository rather than test data. But I'd argue
it's a good start as any.
=> Add --start option to build.js

ios/PolyPodApp/FeatureContainer/FeatureContainerView.swift, ios/PolyPodApp/Features/FeatureStorage.swift, ios/PolyPodApp/PodApi/PolyOut/FS/PolyOut+FS.swift
I was wondering where to best store the _active_ feature - ended up with `FeatureStorage`, whereas it's in `Preferences` on Android. I'd have half a mind to implement it similarly on Android if this one gets approved.
=> PROD4POD-857 - Determine active feature dynamically

features/polyExplorer/src/infographics/featuredEntity.svg, features/polyExplorer/src/infographics/infographics.js, features/polyExplorer/src/locales/de/infographic.json, features/polyExplorer/src/locales/en/infographic.json, features/polyExplorer/src/screens/dataExploration/dataExploration.css, features/polyExplorer/src/screens/dataExploration/dataExploration.jsx, features/polyExplorer/src/screens/dataRegionInfo/dataRegionInfo.jsx, features/polyExplorer/src/screens/explorationInfo/categoryInfo/categoryInfo.jsx, features/polyExplorer/src/screens/explorationInfo/correlationInfo/correlationInfo.jsx, features/polyExplorer/src/screens/explorationInfo/jurisdictionInfo/jurisdictionInfo.jsx
I have taken a look at all the bugs in the **PROD4POD-951** ticket and I have fixed some of the sub-tickets (bugs) in it:
- **PROD4POD-655/Uncontrolled on "how to read" button** (and **PROD4POD-619/Info Button (?) not working in Data Story tab**, both tickets were pointing at the same issue).
- **PROD4POD-618/Info Button (?) not working in Exploration screens**
- **PROD4POD-550/CategoryInfo intro screen -> where does info button lead?** - HTRT button removed from transition screens (screens with only text) in the Exploration screens
=> PROD4POD-951/Fix polyExplorer bugs

features/facebookImport/src/model/analyses/ministories/activities-analysis.js, features/facebookImport/src/model/entities/facebook-account.js, features/facebookImport/src/model/importer.js, features/facebookImport/src/model/importers/messages-importer.js, features/facebookImport/src/model/importers/multiple-files-importer.js, features/facebookImport/src/model/importers/posts-importer.js, features/facebookImport/src/model/importers/utils/failed-import-exception.js, features/facebookImport/test/datasets/posts-data.js, features/facebookImport/test/importers/messages-importer.test.js, features/facebookImport/test/importers/posts-importer.test.js, features/facebookImport/test/mocks/zipfile-mock.js, features/facebookImport/test/utils/data-importing.js, features/facebookImport/test/utils/importer-assertions.js
This imports timestamp for posts and adds them to the mini-stories "Structure of your data" and "Your activities".
Also refactors the messages importer to have a common logic with the posts importers for importing data from multiple files.
=> Partially import posts

features/facebookImport/src/model/analyses/report/importing-status-analysys.js, features/facebookImport/src/model/analyses/report/ministories-status-analysis.js
Missed a CSS warning when adding the column to show the execution time in the report.
=> Fix CSS warning

android/build.gradle, android/java-fetch/build.gradle, android/polyOut/build.gradle, core/communication/bubblewrap/build.gradle
This updates android repositories, mainly due to deprecation on jcenter (which is [not really deprecated](https://stackoverflow.com/questions/66651640/jcenter-deprecation-impact-on-gradle-and-android)).
=> Update Android repositories

features/facebookImport/src/model/analyses/report/report-metadata.js, features/facebookImport/src/model/analysis.js, features/facebookImport/src/model/importer.js, features/facebookImport/test/ministory/importing-status-analysys.test.js, features/facebookImport/test/ministory/ministories-status-analysis.test.js, features/facebookImport/test/ministory/missing-common-json-files.test.js, features/facebookImport/test/ministory/report-metadata.test.js, features/facebookImport/test/ministory/unknown-top-level-folders-analysis.test.js, features/facebookImport/test/mocks/pod-mock.js, features/facebookImport/test/mocks/zipfile-mock.js, features/facebookImport/test/report-creation.test.js, features/facebookImport/test/utils/analyses-execution.js
This ads some tests for the report generation:
- injects the pod into the analyze so features do not have to use window.pod (same API as importers)
- adds a MockedPod for testing
- ads an overall test for the report generation
- tests some individual mini-stories from the report
=> Basic tests for the report

features/facebookImport/test/datasets/ad-views-data.js, features/facebookImport/test/importers/ad-view-language-importer.test.js
We were defining tests for ad views using `test.each`. That has the side-effect that we needed to put all asserts into a single method. This changes the test to call describe on each dataset in a loop, so we can use `it` to structure assertions.
=> Change how tests for ad views are defined

core/communication/remote-pod/package-lock.json, core/communication/remote-pod/package.json
Actually, it's a [weird one](https://app.snyk.io/org/polypoly/project/e2f5d62a-d5e5-49b1-9d2f-afed12391e65) since it's showing up somewhere else. Let's see if this takes care of it. Essentially upgrades electron to the latest version. Can't upgrade electron-mocha, and possibly the best way to go will be to substitute it by some jest-based variant.
=> Upgrades to take care of snyk-revealed vuln

features/facebookImport/src/model/analyses/ministories/post-reactions-types-analysis.js, features/facebookImport/src/model/importers/post-reactions-importer.js, features/facebookImport/test/datasets/post-reactions-data.js
Only take into account known reaction types. There seem to be also other types of reactions in the data, for which we do not have icons at the moment. This avoid a crash in the reactions mini-story if there are unknown reactions.
Pair programming with @mteresa-jimenez
=> Take into account only known reaction types.

core/utils/poly-look/package.json, core/utils/poly-look/rollup.config.js, features/facebookImport/rollup.config.js
I disabled the Rollup plugin we used for minification in polyLook for
now. We'd have to configure it properly so that it ends up exporting all
the necessary global symbols, and currently we win more by having things
easy to debug anyway.
=> Use poly-look.js instead of duplicating the code

android/app/src/main/kotlin/coop/polypoly/polypod/FeatureCardAdapter.kt, android/app/src/main/kotlin/coop/polypoly/polypod/features/Feature.kt, android/app/src/main/kotlin/coop/polypoly/polypod/features/FeatureManifest.kt, android/app/src/main/kotlin/coop/polypoly/polypod/features/FeatureStorage.kt, features/facebookImport/src/static/manifest.json, features/polyPreview/src/static/manifest.json, ios/PolyPodApp/Features/Feature.swift, ios/PolyPodApp/Features/FeatureManifest.swift, ios/PolyPodApp/PolyPod/FeatureListView.swift, ios/PolyPodApp/PolyPod/PreviewUtils.swift
Feature thumbnails are always rendered in the correct aspect ratio -
rather than cut off. As a result, we have some background space to
account for to fill the feature's card.
For this, we used to just use the feature's primaryColor, assuming that
the thumbnail's background colour would always match that one. Turns out
that's not the case, so I gave up and added a dedicated thumbnailColor
field that can be used to overwrite this. If not specified, we fall back
to primaryColor, i.e. the old behaviour.
I specified it for the two features that had a mismatch: facebookImport
and polyPreview.
=> PROD4POD-913 - Add thumbnailColor to feature manifests

features/facebookImport/src/components/postReactionTypesMiniStory/postReactionTypesMiniStory.jsx
Pretty simple one: Calling `reduce` without `initialValue` on an array that could in theory have less than two elements is not a good idea :D
=> PROD4POD-1069 - Fix total for only one type of reaction

android/app/src/main/kotlin/coop/polypoly/polypod/postoffice/PostOfficeMessageCallback.kt, features/facebookImport/src/context/importer-context.jsx, ios/PolyPodApp/PodApi/PostOffice.swift
This one wasn't particularly hard to fix - `polyIn.delete` just can't deal with invalid inputs. Instead of making the APIs more forgiving, I opted to just call it more carefully in the feature - it's the smaller change.
What did take quite a while was reproducing and debugging the problem, due to terrible error messages for invalid arguments. So I took some time to improve those: It's still not pretty, but now we get stack traces based on which we can understand which call caused the issue.
=> PROD4POD-1094 - Fix first time crash in facebookImport

features/facebookImport/src/components/activitiesMiniStory/activitiesMiniStory.jsx, features/facebookImport/src/components/messagesMiniStory/messagesMinistory.jsx, features/facebookImport/src/components/onOffFacebookMiniStory/onOffFacebookMiniStory.jsx, features/facebookImport/src/model/analyses/ministories/activities-analysis.js, features/facebookImport/src/model/analyses/ministories/messages-analysis.js, features/facebookImport/src/model/analyses/ministories/ministories.css, features/facebookImport/src/views/explore/details.css, features/facebookImport/src/views/explore/details.jsx, features/facebookImport/src/views/explore/explore.css, features/facebookImport/src/views/explore/explore.jsx, features/facebookImport/src/views/explore/ministory-styles.css
I went away from the js calculation font-size approach since the numbers were not uniformly sized and it looked odd. Also when coming back from a detail screen you needed to scroll to get the resizing going. This feels better to me but let me know if you have objections.
Also I cleaned up the css so all common analysis css is now in `ministory-styles.css`
=> Fix font size calculation and clean up css styling

android/app/build.gradle
This is a simple upgrade to the first non-vulnerable version mentioned.
=> [fix] {PROD4POD-1026} Upgrade gson to non-vulnerable version

features/facebookImport/src/components/messagesMiniStory/messagesMinistory.jsx, features/facebookImport/src/locales/de/miniStories/messages.json, features/facebookImport/src/locales/en/miniStories/messages.json, features/facebookImport/src/model/analyses/ministories/messages-analysis.js
It appears the new translations used variables that don't exist, and
ultimately really just want the same text that's shown on the story's
summary.
=> PROD4POD-1123 - Fix missing variables in message story details

core/utils/poly-look/src/visualisations/charts/bubble-charts/bubbleCluster/bubbleCluster.js, features/facebookImport/src/components/postReactionTypesMiniStory/postReactionTypesMiniStory.jsx
Trickier than I thought:
`.style("filter", <filter>)` does not work in ios (safari) for SVG's (does so in firefox and only firefox).
Solved by introducing new way filters are added => adding to chart and using on elements when activationContidition is true. 
The good thing is now all kinds of filters can be used and it's not limited to saturate.
=> Prod4 pod 1093/ios saturate

features/facebookImport/src/model/analysis.js, features/facebookImport/src/model/importer.js, features/facebookImport/src/model/importers/utils/importer-util.js, features/facebookImport/src/model/storage.js, features/facebookImport/test/mocks/zipfile-mock.js
(Still a draft)
This caches the list of files inside `ZipFile`. 
A further improvement would be for importers to use `hasEntry` instead of manually iterating through the list of files.
Another possible improvement for a later PR could be to refactor `analyzeFile` and  `importData` to pass the same zip file.
=> Cache list of files from the zip

android/app/src/main/kotlin/coop/polypoly/polypod/features/FeatureStorage.kt, android/app/src/test/kotlin/coop/polypoly/polypod/features/FeatureStorageTest.kt, features/bundle/package.json
Changed things to the desired order, and also hid polyExplorer V2 and
demo while at it.
On Android, we would still show features present on disk but not present
in the generated order file. Changed this behaviour for now, since we
got into the habit of adding features temporarily for testing purposes.
=> PROD4POD-1131 - Reorder and clean up feature list

android/app/src/main/kotlin/coop/polypoly/polypod/MainActivity.kt
Originally it seemed like a bad workaround on iOS to just authenticate
in a loop, but turns out in practice it's a lot better than just closing
the app after one failed attempt.
Turns out the solution was pretty simple - just relaunch the activity
when authentication fails. I'm mildly surprised it works as intended,
but according to my tests it does.
=> PROD4POD-1097 - Relentlessly authenticate on Android as well

features/facebookImport/src/i18n.js, features/facebookImport/src/locales/de/facebookAccount.json, features/facebookImport/src/locales/en/facebookAccount.json, features/facebookImport/src/model/entities/facebook-account.js
Turns out these strings were just hard coded so far. While we do control
them, they are technically Facebook terminology and if possible we would
probably want to use _their_ translations, therefore I moved them to a
dedicated translation file.
=> PROD4POD-1049 - Translate structure chips

ios/PolyPodApp/FeatureContainer/FeatureContainerView.swift, ios/PolyPodApp/Features/Feature.swift, ios/PolyPodApp/Features/FeatureStorage.swift, ios/PolyPodApp/PodApi/Network/Network.swift, ios/PolyPodApp/PodApi/PolyIn/Quads/PolyIn+Add.swift, ios/PolyPodApp/PodApi/PolyOut/FS/PolyOut+FS.swift, ios/PolyPodApp/PodApi/PostOffice.swift, ios/PolyPodApp/PolyPod.xcodeproj/project.pbxproj, ios/PolyPodApp/PolyPod/AppDelegate.swift, ios/PolyPodApp/PolyPod/Authentication.swift, ios/PolyPodApp/PolyPod/FeatureView.swift, ios/PolyPodApp/PolyPod/FilePicker.swift, ios/PolyPodApp/PolyPod/Log.swift
This should make it easier for us to understand crashes we cannot
reproduce. In my understanding, all the error level log messages we
write, are being stored on the device. Info level log messages aren't,
but I think all the cases I used info for are not incredibly helpful for
debugging issues that happen in the wild.
I did improve _some_ log messages, but there's still a lot of work to do
in terms of making them consistent, not duplicating the same strings so
much, and being more specific about where an issue occurred. A large
chunk of our error log messages in the API code also needs to throw an
actual error, so that it can propagate back to the feature. As opposed
to Android, a lot of errors are currently being swallowed.
But still, I think this is a good first step.
=> Add proper logging on iOS

build/index.js
This should help us understand which parts of the process are slow.
While at it, I also reduced the noise a bit by adding
--no-update-notifier (and --no-fund, for good measure), to all NPM
invocations.
There's room for improvement though:
1. I experimented with adding a --quiet option for build.js that
surpresses all of the actual build output, but took longer than a few
minutes so I didn't bother at this point. It's easy enough to comment
out the console.log statements in executeProcess temporarily :P
2. We're invoking NPX for linting - that doesn't print any timings ATM,
but I suppose we're not too interested in those execution times so I
didn't bother for now.
=> Print per-package build timings

build/index.js, package.json
By fleshing out the very barebones package.json we had, and simply adding a request to do it in the code. While I was at it, I've added a couple of keys to that same file, with reasonable defaults (including the name of the package).
=> Cleans up (using build.js clean) at the top level

.github/workflows/ios-test.yml
Not a lot, but enough. Originally intended to spin off the build step, but it's just a command, so it eventually ended up this way.
=> Restrict build paths

core/utils/poly-look/.storybook/server.mjs, core/utils/poly-look/package-lock.json, core/utils/poly-look/package.json, core/utils/poly-look/web-test-runner.config.mjs
This continues cleanup of poly-look. In this case apparently there were some dependencies that were just mentioned in a comment. Deleted comments, eliminated dependencies, as well as `prettier`, which should have been eliminated a long time ago.
The rest of the changes have been made by VSCode as linting. 
To be honest, I'm not totally sure what those files *actually* do. But that will need a bit of research. Eventually we might want to substitute all the myriad packages by `cypress`, but how to do so is not trivial.
=> [Fix] Eliminate web dev server

android/app/src/androidTest/kotlin/coop/polypoly/polypod/CommunicationThroughPodApiWorks.kt, android/app/src/androidTest/kotlin/coop/polypoly/polypod/FeatureFragmentInstrumentedTest.kt, android/app/src/androidTest/kotlin/coop/polypoly/polypod/PodApiTestDouble.kt
Some old Android integration tests currently don't compile - they were a
bit experimental in the first place, and never got updated along with
other refactoring we did, because we never ran them.
Recently, we started to add some more meaningful integration tests we
actually _do_ want to make sure we run. So in order for it to make it
easy to run these, I've commented out the broken ones for now. Only a
temporary measure for sure.
=> Fix Android tests

features/facebookImport/src/model/analyses/ministories/about-pictures-data-analysis.js, features/facebookImport/test/ministory/about-pictures-data-analysis.test.js
In newer exports photos are at `posts/media`. Before they were in the `photos_and_videos` folder. This takes both these folders into account in the `AboutPicturesDataAnalysis` mini-story.
=> Take the new path for photos into account.

features/polyExplorer/src/components/entityList/entityList.css, features/polyExplorer/src/components/entityList/entityList.jsx, features/polyExplorer/src/components/entityShortInfo/entityShortInfo.css, features/polyExplorer/src/screens/stories/digitalGiantsStory.jsx, features/polyExplorer/src/screens/stories/messengerStory.jsx
While working on this, I had to make some more improvements to EntityList:
1. Add an attribute to expand it, avoiding all the infinite scrolling logic -
Probably works without, but it seemed wrong to run all that code we know is
not needed.
2. Avoid re-render loops when using entity arrays - the useMemo I added.
3. Removing the hard coded background from EntityShortInfo - funny enough,
that's all it took in terms of "theming", CSS FTW.
=> PROD4POD-621 - Add Explore Further sections

core/utils/silly-i18n/src/index.js, core/utils/silly-i18n/test/basic.test.js, core/utils/silly-i18n/test/section.test.js, features/polyExplorer/.gitignore, features/polyExplorer/src/components/dataRegionsLegend/dataRegionsLegend.jsx, features/polyExplorer/src/components/discoverCard/discoverCard.jsx, features/polyExplorer/src/locales/en/stories/clusterStoriesPreview.json
Essentially, try to reduce boilerplate by creating a new class that includes as attribute the `section` (called "header" sometimes) that's reused in most, if not all, polyExplorer (and others) files.
Also:
* improve a bit documentation by indicating types and default values (after pioneering work done by @RichardSto )
* Refactor a couple of polyExplorer components to use this new feature.
> Come to think of this, the pattern should actually be inverted: a i18n object should be constructed out of a set of Section objects, which should also be enabled to work by themselves. That would avoid the [usual pattern](https://github.com/polypoly-eu/polyPod/blob/main/features/facebookImport/src/i18n.js)
=> [Task] {PROD4POD-1194} Trying to make silly-i18n more serviceable to current usage (in polyExplorer and others)

core/api/pod-api/src/api.ts, core/api/pod-api/src/default.ts, core/api/pod-api/src/spec.ts
My initial idea was to eliminate `readdir` from `FS`, but it's actually used somewhere. Finally did a bit of refactoring mainly renaming identifiers and changing a bit the default implementation so that it actually uses a (roughtly) unique ID for `Entry` `id`
> It might not be a bad idea to enforce that's an ID by making it, for instance, an URI (which, IIRC, is what it actually is).
Also added a bit of doccing for good measure.
=> Refactoring and documentation

.gitignore, core/api/manifest-parser/.npmignore, core/api/manifest-parser/rollup.config.js, core/api/manifest-parser/src/manifest.ts
For the time being, it's just a bit of maintenance, bringing it up to date, eliminating deprecations and old files. It sets the stage for further documentation and actual use in the features, as indicated in PROD4POD-1214.
> There are a couple of TODOs that I can't figure out. This is the reason why we should never commit TODO comments to main, and possibly neither we should do it to branches.
=> [Chore] {PROD4POD-1214} Manifest-parser maintenance

.github/workflows/ios-test.yml, .github/workflows/test.yml, build/README.md
To be able to use advanced cache features. Using the latest node version for LTS 16 instead of locking to 16.8, which was done because of a node upgrade snafu. That's the least important, however, what matters is that the new `setup-node` is able to cache all node_modules from scratch, without needing complicated setups.
This is saving quite a bit, a couple of minutes when cache is hit. Might be more in iOS, taking into account the unpredictable nature of that. And it might be even more, if we eliminate auditing from the build (which we probably should)
> Changes in the README.md were done to trigger builds, although they should probably stay anyway.
It's a 4 minute difference in iOS
Reducing total time by almost 40% So it's a big win.
=> Upgrades set-up node

ios/PolyPodApp/PolyPod/AppDelegate.swift
By attempting to log the number of quads stored in the triple store, we
are enforcing it to be initialised unnecessarily early - presumably in
some situations before the device is unlocked.
=> PROD4POD-1078 - Delay initialisation of Core Data

build/index.js, package.json
I wanted to make it independent from #578 to assess the impact, if there's any.
> In fact, there's none since when installing from scratch, auditing is done at the self same time. So this PR is mainly a no-op in terms of time.
I'll use this PR to make some more, mostly cosmetic, changes to `build.js`, to understand more clearly what's going on.
There does seem to be a speedup in iOS, see [this](https://github.com/polypoly-eu/polyPod/runs/4699607045?check_suite_focus=true) vs [this](https://github.com/polypoly-eu/polyPod/runs/4699579215?check_suite_focus=true) but MacOS in GHA is so unpredictable, that who know what's happening here.
=> Different speed-ups to the install/build process

build/index.js
The use case for this is when there are some security updates in an upstream package (anything in core), that's included also in the `package-lock.json` of downstream dependencies (features). So it was incredibly tedious to rebuild every single package from the one that had been modified. If it was a cornerstone package such as `pod-api` it needed *a lot* of `cd`ing and `npm i`ing.
This, together with the `--start` feature that @fhd added, will really simplify and save a lot of time (mine mainly for the time being, but who knows)
=> Adds sync to the build script

features/polyExplorer/src/static/images/stories/digital-giants/card-image.svg, features/polyExplorer/src/static/images/stories/messenger/card-image.svg
These were introduced by 25606f1f2de9288ab987a5d09dcce942b6c2dbd3 - I
think it was an accident. Given how we get those SVG images from
designers, I don't think we want to ever manually modify them.
=> Fix black SVG artefacts

core/utils/dummy-server/package-lock.json, core/utils/dummy-server/package.json
Takes care of [this alert](https://github.com/polypoly-eu/polyPod/security/dependabot/core/utils/dummy-server/package-lock.json/engine.io/open). Since `dummy-server` is just that, used for tests and so on, making it crash is not such a great deal so impact is not exceptional, but then we don't know what this is going to be used for in the future, and it's just an upgrade to a newer version that might improve performance and suchlike. So we're in with that.
=> Upgrades socket.io → engine.io

package-lock.json, package.json
Mainly to take care of [this vulnerability](https://github.com/polypoly-eu/polyPod/security/dependabot/package-lock.json/shelljs/open). It does not look as if we're really affected by it, but OTOH, upgrading one notch is not such a big deal, so I guess it's OK.
=> Upgrade shx → shelljs

.github/workflows/test.yml, android/app/build.gradle, android/app/src/main/kotlin/coop/polypoly/polypod/FeatureFragment.kt, android/build.gradle, android/gradle/wrapper/gradle-wrapper.properties, android/java-fetch/build.gradle, core/communication/bubblewrap/build.gradle
As usual, this is a revision of the Android build looking for possible upgrades; main issue here was the upgrade of the Gradle plugin for Android studio and fixing of the corresponding problems with outdated Gradle configurations. Fell free to comment or outright dismiss.
I would say the only major change, besides the gradle plugin (that has leapt 3 majors) is the Java version in the test configuration. The rest are minor changes, some version upgrades, elimination of jcenter almost everywhere. This should have no major impact, except prevent from deprecations in the near future (they will hit us anyway)
> Would it be interesting to consider [this new implementation of CarouselView](https://github.com/jama5262/CarouselView) which is in a Maven repository?
I've compiled it locally with …
=> Android build maintenance

.gitignore
These will crop up when you start to use `jsdoc`/`typedoc`
=> Add docs to ignored directories

android/app/src/main/kotlin/coop/polypoly/polypod/polyOut/PolyOut.kt
Since it doesn't seem to work on API 24. It's probably better this way
anyway, because we don't explicitly have commons-io as a dependency,
it's pulled in through Jena it seems.
=> PROD4POD-1242 - Replace FileUtils.sizeOfDirectory

core/utils/poly-look/src/react-components/tabs/tabs.jsx, features/polyExplorer/src/components/clusterStories/receivingCompanies.jsx
In order to anchor the info button to the right, the button was removed from the individual tabs and inserted into the parent component. A useState was implemented to keep track of the active tab and now a custom callback can be triggered every time the tab is changed.
=> HTRT info button keeps track of activeTab

features/polyPinion/package.json
This was the only place it was used, and it was empty. So better eliminate it to avoid confusion.
> The whole `polypoly` section is probably unused either; it's only here and in `example`. But that can wait, I guess.
=> Eliminates apparently unused package.json key polypoly → manifest

features/polyExplorer/src/screens/stories/messengerStory.jsx
Facebook had been changed to meta in the strings, but not in the code.
=> Facebook was substituted for meta

features/facebookImport/package.json
Although documentation is not generalized, there are few modules that are actually documented. Adding this might encourage documentation of the rest, and notably help devs to check out documentation in a single place (beyond tool tips by VSCode)
=> Add doc generation target to FacebookImport

ios/PolyPodApp/PolyPodUITests/UpdateNotificationTest.swift
There were some flapping errors in the iOS workflow, such as [this one](https://github.com/polypoly-eu/polyPod/runs/5212584962?check_suite_focus=true). These looked like timeouts, so I added this wait state to try and avoid them. Main idea is the timeout, which can be extended I guess if it keeps failing.
Also my first actual Swift code PR, so please be lenient with me here.
=> Adding a wait state to avoid timeouts

.github/workflows/rust_kernel_tests.yml
Add CI to test and lint the Rust kernel.
Kudos to @JJ for original implementation [here](https://github.com/polypoly-eu/polyPod-platform-core-experiments/blob/main/.github/workflows/rust-test.yml)
=> PROD4POD-1336: Add test CI for Rust

3rd-party-licenses/rust-licenses.txt, core/kernel/Cargo.lock, core/kernel/Cargo.toml, core/kernel/src/feature_manifest.rs, core/kernel/src/lib.rs
- Added feature manifest parsing:
- Parsing from JSON.
- Locale handling.
- Tests. 
- Used [serde_json](https://docs.serde.rs/serde_json/) for parsing, the "go to" solution in Rust, as it does not have native json parsing capabilities.
- Added the required licenses.
=> PROD4POD-1363: Kernel - feature manifest parsing

features/polyExplorer/package-lock.json, features/polyExplorer/package.json
Move a dependency to where it (I guess) belong, also unifying d3 versions with poly-look
=> Fix deps 🔧

dev-utils/dummy-server/package-lock.json, features/bundle/package-lock.json, features/demo/package-lock.json, features/example/package-lock.json, features/facebookImport/package-lock.json, features/lexicon/package-lock.json, features/polyExplorer/package-lock.json, features/polyPinion/package-lock.json, features/polyPreview/package-lock.json, features/test/package-lock.json, platform/feature-api/api/pod-api/package-lock.json, platform/feature-api/communication/remote-pod/package-lock.json, platform/podjs/package-lock.json
After `package.json` was updated with the new path for `dummy-server`, lockfiles were not. This is an update of all files depending on that.
=> [Fix] {PROD4POD-1443} Update all lockfiles after rearrangement

feature-utils/silly-i18n/cypress/integration/browser_spec.js, feature-utils/silly-i18n/src/index.js, feature-utils/silly-i18n/src/l12n.js, feature-utils/silly-i18n/test/basic.test.js, feature-utils/silly-i18n/test/l12n.test.js, feature-utils/silly-i18n/test/test-utils.js
We had some localization (l12n) capabilities in `silly-i18n`, but now I'm spinning them off to its new module and extending capabilities. At least, I'll try to account for numbers and dates, these being the ones that can be easily identified (more or less)
To do:
=> [Task] {PROD4POD-122} Add a real l12n module

platform/android/app/src/main/kotlin/coop/polypoly/polypod/polyOut/PolyOut.kt
A coroutine can block the main thread if it performs a heavy job, thus this change dispatches the archive unzipping to IO thread so that main thread(which is used for UI) is unblocked. This way the app is usable while the archive is imported, and this should fix the ANR.
This fix is similar to -> https://github.com/polypoly-eu/polyPod/pull/595. It seems that Android and iOS apps are running everything(or almost) on the main thread. While for simple operations this is acceptable; heavier operations need to be offloaded to other threads to free the main thread for UI jobs triggered by the OS, for example screen refresh. Executing lots of operations on the main thread will decrease the application's frame rate down to being unresponsive. We may need to investigate the apps for other cases, …
=> Dispatch archive unzipping to IO context

features/polyPinion/rollup.config.js, platform/podjs/rollup.config.js
Mainly configures them as external dependencies to avoid the warning. There's still a circular dependency warning in pod.js, but it's not our code, but `semver`
=> [Fix] Rollup ⚠ in two modules

.github/workflows/js-and-android-test.yml, platform/android/README.md
Java can be cached, so why not. Might not work due to the fact that we have our files elsewhere, but wanted to check just in case. It needed an upgrade of the GitHub action, and a (mostly random) selection of the Java distribution (previously Zulu was used, can be used too). As can be seen above, 2 minutes saved!
=> Cache Java

package-lock.json, package.json
After my patch was included in a release. This was showing up in every build, for instance [this one](https://github.com/polypoly-eu/polyPod/runs/5364331658?check_suite_focus=true):
Not a terribly disabling feature, but annoying nonetheless (and installing a dependency that was actually unneeded)
=> ⬆ cypress to eliminate querystring warning

.editorconfig
Was starting to drive me crazy that my editor would (correctly) stick to the four space indents configured for the repo, when we use two space indents across all our GA workflow YAML files :D
=> Set indent for GA workflow files

.github/workflows/upload_app_store.yml, platform/ios/Makefile
1. Eliminate `$(value)` workaround for reading secrets from env variables
2. Replace `echo` with `printf` to support multi line secrets (though we don't have any at the moment)
3. Make local variables defined by us lower case
4. Mark all phony targets as phony
5. Wrap at 80 columns
=> Refactor the iOS Makefile a bit

feature-utils/poly-look/storybook/package-lock.json, features/polyPreview/package-lock.json
Upgrades minimist to 1.2.6 via `npm audit fix`. These two were left over in #766.
=> 🐛 minimist part deux

.github/workflows/upload_all.yml
Use updated r0adkll/upload-google-play@v1.0.16 instead of our fork.
=> PROD4POD-1426 Fix: r0adkll/upload-google-play 

features/test/src/test.ts
These warnings were still showing up, for instance [here](https://github.com/polypoly-eu/polyPod/actions/runs/2039102319). `select` is also deprecated, so I changed it while I was editing the file.
=> Eliminate ⚠ resulting from fetch spec 3

.github/workflows/rust_kernel_tests.yml
[Syntax](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions) was apparently incorrect, you can avoid single quotes only with whole words.
=> Fix → The rust linter was always firing

.github/workflows/ios-android-test.yml
=> Limit instrumentation tests to push, and only release and main

platform/podjs/rollup.config.js
This was a `rollup` warning appearing everywhere, for instance [here](https://github.com/polypoly-eu/polyPod/runs/5766280202?check_suite_focus=true)
By upgrading the configuration, it's been eliminated without affecting functionality.
=> Fixes ⚠ by defining externals and context

.eslintrc.cjs, platform/feature-api/api/rdf-spec/.eslintrc.js, platform/feature-api/api/rdf/.eslintrc.js
To be honest, this was caused mainly by the sudden occurrence of linting errors when modules in the `feature-api` directory are moved around, for instance [here](https://github.com/polypoly-eu/polyPod/actions/runs/2088708981). There are many errors there that were, apparently, ignored for some reason I can't fathom.
That happened also in #763, so I took to revise the configuration. I still don't know why it fails, but I found nonetheless directories that no longer existed, and some configuration files that are not really used.
=> Maintenance esLint configuration

features/google/package-lock.json, features/google/package.json, features/google/src/context/google-context.jsx, features/google/src/model/importer.js
Fixes build by changing everything to the new name; the `google` feature had not changed.
> Seemingly unrelated change is simply the IDE sorting dependencies.
=> [Fix] {PROD2POD-1507} Fixes build

feature-utils/poly-import/src/storage.js
The refresh files function is currently placing an incorrect key to the object that stores all the directories in side of the statResults object which then becomes the Features files. This correction is meant to help correctly store the Feature files using a valid key such as the file id. 
before #560 this was the file id&path conjugated string.
=> statResults keys are now file.id

.github/workflows/upload_all.yml, features/facebookImport/rollup.config.js, platform/podjs/src/browserPod.ts, platform/podjs/src/json-typings.d.ts, platform/podjs/tsconfig.json, platform/utils/endpoints-generator/endpoints.js, platform/utils/endpoints-generator/index.js
On this PR, we enable `podjs` to read external JSON files by setting the flag `--resolveJsonModule` in `tsconfig` and adding a  `typings.d.ts` on `src` root, which enables TS to actually read the imported JSON file without complaining.
This way, we don't need to "hack" anymore the import of "endpoints.json" by setting ts to "ignore" this import.
Grabbing the chance, we introduce a stricter type `EndpointJSON` for the endpoints Json format so we make sure that `getEndpoint()` retrieves back the correct object as now the passed arg can only be a key of this JSON (aka either `polyPediaReport` or `demoTest`)
Thank you 🌷
=> fix ts config to read external JSON files in podjs

feature-utils/poly-look/package-lock.json, features/polyExplorer/package-lock.json
This was in a test dependency, but anyway. `audit fix` was more than enough; downstream modules have not been updated for the time being.
=> [🐛] {PROD4POR-1514} async vulnerability eliminated

features/bundle/package-lock.json, features/facebookImport/package-lock.json, features/google/package-lock.json, features/lexicon/package-lock.json, features/polyPreview/package-lock.json
Opened [issue](https://github.com/modernweb-dev/web/issues/1934) in the dependency that includes it, but since it's two modules removed and one of them (`portfinder`) seems stale, I don't see a chance of this being fixed any time soon. `npm audit fix` works just fine.
=> 🐛 async redux

features/example/src/index.jsx, features/facebookImport/src/views/import/import.jsx, features/polyExplorer/src/context/explorer-context.jsx, features/polyPinion/src/util/async-storage.ts, features/test/src/index.html, features/test/src/test.ts, platform/android/app/src/androidTest/kotlin/coop/polypoly/polypod/CommunicationThroughPodApiWorks.kt, platform/android/app/src/androidTest/kotlin/coop/polypoly/polypod/polyIn/PolyInTestDouble.kt, platform/android/app/src/main/kotlin/coop/polypoly/polypod/PodApi.kt, platform/android/app/src/main/kotlin/coop/polypoly/polypod/polyIn/PolyIn.kt, platform/android/app/src/test/kotlin/coop/polypoly/polypod/polyin/PolyInTest.kt, platform/feature-api/api/pod-api/package.json, platform/feature-api/api/pod-api/src/api.ts, platform/feature-api/api/pod-api/src/default.ts, platform/feature-api/api/pod-api/src/spec.ts, platform/feature-api/communication/remote-pod/src/async.ts, platform/feature-api/communication/remote-pod/src/remote.ts, platform/ios/PolyPodApp/PodApi/PolyIn/CoreData+PolyIn.swift, platform/ios/PolyPodApp/PodApi/PolyIn/PolyIn.swift, platform/ios/PolyPodApp/PodApi/PostOffice.swift, platform/podjs/src/browserPod.ts
It was substituted by match, and in fact all implementations were exactly the same. Since #810 is coming, there's no need to implement this too.
=> [Fix] {PROD4POD-1518} Eliminate code that was deprecated 7 months ago: select

feature-utils/poly-look/src/poly-look.js
Lately, I've had a few too many merge conflicts in this file and in `react-components/index.js` . While I think the latter should stay as it is just so you have a place where you can see all the components, the former can be changed since it seems to only serve as an entry point for the bundler.
=> ref (poly-look) - simplify poly-look.js

.github/workflows/js-and-android-test.yml, build/index.js
As exemplified by the latest failure in [this latest PR](https://github.com/polypoly-eu/polyPod/runs/6197622974?check_suite_focus=true)
It's likely that there was one error when solving a conflict when updating the workflow. As a matter of fact there was a cache miss, but the path that checked if `install` was needed was not triggered, due to that mismatch between the updated name and the updated patch check.
> Surprisingly (maybe not), `build` only needs root installs. I guess that since what's involved in build: babel, TS, rollup, is mostly hoisted, it would fail only if there were some specific rollup plugin somewhere. Clarifying dependencies is good.
=> Fix workflow and build issues

platform/podjs/rollup-plugin-gen-podjs/genPodjs.js
It was previously skipping the pod.js copy, because the 'public'
directory already existed - it happened to work with our other features
because pod.js was going right into the build directory ('dist') there,
and the genPodJs plugin happened to be the first one to be called.
I believe the logic is now what it was supposed to be originally -
merely ensuring that the directory pod.js is supposed to be copied into
actually exists.
=> Fix pod.js generation in lexicon feature

platform/podjs/src/browserPod.ts
For context, see https://jira.polypoly.eu/browse/PROD4POD-1521
I might prefer to use `manifest.name` for the scope rather than the path, but it appears that not all features implement `window.manifestData`?
Also with this PR, I removed the migration logic. If we are transitioning form a shared storage to a feature specific storage, how are the previously globally stored data supposed to carry over? Should they even carry over as the reason for this change is that having data shared between features caused issues?
=> Isolate storage per feature in pod.js

.github/workflows/js-and-android-test.yml, build/README.md, build/cli.js, build/index.js, build/npm.js, build/pkg.js
There are many changes in this PR, while trying to stick to its spirit, which is making builds work from the first time.
1. `install` now, by default, does not `prefer-offline`. It will run `npm ci --no-audit` on every package. It will also run a root install every time.
2. `installAndBuild` will also run a root install
3. A new commandm `offlineInstall` has been added. This is run from CI instead of `install`, since it does not have any problem as apparently caches in the CI runner are pre-populated. This is used now instead of `install` in CI, so that it's got the same behavior as before.
4. Lint is now run before install, since `lint` by default will run a root install if it does not find `node_modules`.
Some changes have been made to the README, although this would definitely need …
=> [🐛] {PROD4POD-1549} Try and avoid first-time build errors by adding a new setup command

feature-utils/poly-import/src/storage.js, platform/podjs/src/browserPod.ts
Trying to open the google feature with pod.js, I got a runtime error,
since apparently the object returned from pod.js' implementation of, I
presume, polyOut.stat, does not have an incidental "id" property
anymore.
=> Fix zip file reading via pod.js

platform/AppStoreConnect/Sources/AppStoreConnect/AppStoreConnect.swift, platform/AppStoreConnect/Sources/AppStoreConnect/CreateBetaBuildLocalization.swift, platform/AppStoreConnect/Sources/AppStoreConnect/ReleaseToExternalTesters.swift, platform/AppStoreConnect/Sources/AppStoreConnect/SubmitAppForBetaReview.swift
Before the build is sent to testers, it has to be sent to beta app review.
What was added:
- Add `What 's new` text for the build.
- Submit build for beta review.
=> PROD4POD-1553: AppStoreConnect submit build for beta review

feature-utils/poly-look/src/react-components/filterChips.jsx, feature-utils/poly-look/test/react-components/filterChips.test.js
Yeah thats a weird one. Apparently the Filterchips were broken when you press a bubble.
It doesn't really have a way to update chips from outside. This should be just a dumb component without state, BUT the "all" and "others" chip used in polyExplorer make this quite complicated logic which i wouldn't want to repeat.
Soooo I added another state to compare the current state to the original one, so when the defaultChip changes from outside it'll change on the inside. Yeah just a hack for now..
=> Fix the Filterchips

platform/ios/PolyPodApp/PodApi/PostOffice.swift
An error was returned when a quad was not found.
Now, no error is returned in either case. A boolean indicating the whether the search was successful is returned for the response as a MessagePackValue.
I don't know how to test this yet. I am figuring it out.
=> [PROD4POD-1211] iOS: polyIn.has throws an error instead of returning false

platform/android/app/src/main/kotlin/coop/polypoly/polypod/Authentication.kt, platform/android/app/src/main/kotlin/coop/polypoly/polypod/MainActivity.kt, platform/android/app/src/main/kotlin/coop/polypoly/polypod/OnboardingActivity.kt, platform/android/app/src/main/kotlin/coop/polypoly/polypod/Preferences.kt, platform/android/app/src/main/kotlin/coop/polypoly/polypod/polyOut/PolyOut.kt, platform/android/app/src/main/kotlin/coop/polypoly/polypod/settings/MainFragment.kt, platform/android/app/src/main/res/values-de/strings.xml, platform/android/app/src/main/res/values/strings.xml, platform/android/app/src/main/res/xml/settings.xml, platform/ios/PolyPodApp/Extensions/BindingExtensions.swift, platform/ios/PolyPodApp/PolyPod.xcodeproj/project.pbxproj, platform/ios/PolyPodApp/PolyPod/Authentication.swift, platform/ios/PolyPodApp/PolyPod/ContentView.swift, platform/ios/PolyPodApp/PolyPod/OnboardingView.swift, platform/ios/PolyPodApp/PolyPod/SettingsView.swift, platform/ios/PolyPodApp/PolyPod/de.lproj/Localizable.strings, platform/ios/PolyPodApp/PolyPod/en.lproj/Localizable.strings
🏗️ 
With this PR change, we allow users to turn PIN/biometrics authentication on/off via settings, and not only in Login/Onboarding phase.
It regards changes on both iOs and Android platforms, where the user is required to re-authenticate with their PIN/biometrics when they're turning the option on or off via a toggle button.
It mainly includes:
- Addition of toggle button in UI
- Addition of 'disable()' to handle the setting's off status
- Call Biometrics to re-authenticate 
- Set new value of "biometrics"/"authorization" key in Preferences
- Handle callbacks so we update value in UI when we've the result
- minor refactorings on the go
when setting is off:
when we toggle the button to on, it triggers a re-authentication:
the result when back to settings:
Note:
I haven't seen any tests …
=> Introduce re-authentication option in settings - PROD4POD1091

platform/ios/PolyPodApp/PolyPodUITests/UpdateNotificationTest.swift
This was timing out repeatedly lately, for instance [here](https://github.com/polypoly-eu/polyPod/runs/6391074448?check_suite_focus=true). The error was reported like:
```
Executed 5 tests, with 1 failure (0 unexpected) in 53.690 (53.694) seconds
```
So I guess we need to increase the timeou to 60 seconds. That would reduce the likelihood of this failing. The first attempt (in #315) did result in some improvement until now, maybe due to degraded performance of the OSX runner or some unrelated thing.
=> Increase timeout in iOS tests

dev-utils/windows/README.md
Could have a line-break but then with the whole command.
Should be `../..` right?
=> Fix small windows util path

platform/core/Makefile
Although rustup was installed, `hash` was not working.
=> [Fix] Using a different way of checking for rustup

.eslintrc.cjs, build/.eslintrc.json, feature-utils/poly-look/.eslintrc.js, feature-utils/silly-i18n/.eslintrc.cjs, features/polyPreview/.eslintrc.js
This came up in #860 where I'd like to use the `||=` operator but unless we advance `parserOption.ecmaVersion` to `2021` in the ESlint configuration, ESLint will fail to parse any script using the new operator.
It seems to be sufficient to just set this setting in the top-level ESlint configuration and if we stop overriding it in the configurations down the source tree.
=> Bump up ECMA version of ESLint's parser

.eslintrc.cjs
Flatbuffers included a number of TypeScript files, that were yielding false positives in linting, at least if you had made a core build locally; no issue in the global CI
=> Avoid flatbuffers code being linted

platform/core/.eslintrc
Avoid version issues by using the whole directory. This is in place of #881 reverted by #883
=> [🙈] Eliminate linting errors by configuring in the proper place.

platform/podjs/rollup.config.js
In #810, I introduced the `rdf-string` package. Since then when building *pod.js*, Rollup emits various `[...] is not exported by node_modules/rdf-string/index.js` warnings. Apparently, `rdf-string` is the only package bundled that is distributed as CommonJS, and we never configured the `commonjs` plugin for the `index.js` build target.
=> Fix missing export warnings when building podjs

feature-utils/silly-i18n/rollup-plugin.cjs
By default the  `I18n` class selects the first language in the provided translations as fallback language (i.e. the language used instead if there are no translations for the requested language). Before #860, the translations for `en` always came first in the manually maintained boilerplate. But now where the code initializing the `I18n` class is generated, the languages occur in alphabetic order which makes `de` the implicit fallback language.
=> Make "en" explicit fallback language

platform/android/app/build.gradle, platform/ios/PolyPodApp/PolyPod.xcodeproj/project.pbxproj
We already did encounter scenarios when updating some file paths, or some scripts did fail to generate the bundle resources, the Android and iOS builds where successful, only for us to find the issues after the app was published to testing.
Instead of having a silent fail and producing a successful build, now the build will fail if resources are missing, acting as a sort of integration test.
=> Safeguard bundle resources for iOS/Android

feature-utils/silly-i18n/rollup-plugin.js, features/facebookImport/rollup.config.mjs, features/google/rollup.config.mjs, features/lexicon/rollup.config.mjs, features/polyExplorer/rollup.config.mjs, features/polyPreview/rollup.config.mjs, platform/podjs/rollup-plugin-gen-podjs/genPodjs.js, platform/podjs/rollup-plugin-gen-podjs/package.json
When I introduced `@polypoly-eu/silly-i18n/rollup-plugin.cjs` in #860 I made it a CommonJS module to keep the changes in that PR as minimal as possible. In order to use a Rollup plugin in ESM format that is referenced as a package you have to prevent Rollup from transpiling the configuration script (by using the `.mjs` file extension). That's because the configuration script  is transpiled to CommonJS and therefore cannot import external ESM modules.
=> Convert feature-utils/silly-i18n/rollup-plugin.cjs to ESM

platform/podjs/src/browserPod.ts
* Use an index instead of managing arrays of files
* Restore logic for handling files not contained in a ZIP file
* Fix regressions breaking google and facebookImport features
*  Undo some unrelated changes from #857
=> Clean up podjs implementation of PolyOut after multi archive refactoring

features/google/src/components/importExplanationExpandable/importExplanationExpandable.css, features/google/src/components/importExplanationExpandable/importExplanationExpandable.jsx
When files is empty and loaded (`[]`) then is is still `true`. So we need to check for length. Also disabling the button with new CSS
=> Fix bug and disable button

platform/android/app/src/main/kotlin/coop/polypoly/polypod/MainActivity.kt, platform/core/PolyPodCoreAndroid/core/src/main/java/coop/polypoly/core/Core.kt, platform/core/PolyPodCoreAndroid/core/src/main/java/coop/polypoly/core/CoreExceptions.kt, platform/core/flatbuffers_shared/flatbuffer_models/failure.fbs, platform/core/src/core.rs, platform/core/src/core_failure.rs, platform/core/src/flatbuffers_mapping/core_bootstrap_fbs_mapping.rs, platform/ios/PolyPodApp/PolyPod/AppDelegate.swift
Instrumentation tests might restart the app without clearing its memory several times, thus ignore the error thrown by core when it is already bootstrapped, which is in no way a breaking failure.
=> Do not crash the app if core is already bootstrappped

platform/android/app/src/main/kotlin/coop/polypoly/polypod/polyOut/PolyOut.kt, platform/ios/PolyPodApp/PodApi/PolyOut/FS/PolyOut+FS.swift
The problem was that readDir and stat have used a different definition of "id". One with prefix and one without
We have path, url and id and they seem to get mixed up
=> Fix ios bug

.eslintrc.cjs
This just generates noise during local linting.
=> Avoid 🧹 downloaded tools

feature-utils/silly-i18n/rollup-plugin.js
It seems that the `glob` module returns POSIX style paths regardless of the os, while our solution was cross platform and was expecting a windows style path when trying to determine the language.
There might be better ways of fixing this, but this is the quickest I could think of.
=> fix: prod4pod-1602 sillyI18n Rollup plugin doesn't work on Windows

dev-utils/rollup-plugin-copy-watch/package.json, platform/utils/endpoints-generator/package.json
Which is `index.js`
> The rest are probably OK, although in some cases it points to the source (`src` directory) and in others to the `dist` bundled directory. In the case of `pod.js` it's probably wrong, as well as probably not needed anyway (since it's mainly copied, not included as a module); in the rest, it's probably OK, although the fact that it uses generated code needs to be accounted for.
=> Delete «main» key in package.json where it takes the default value.

.github/workflows/js-and-android-test.yml, platform/core/Makefile
This step takes 4 minutes, and it compiles a ton of things. It would be nice to cache, but I'll need to find out what can be fruitfully cached and what not (for instance, caching a zipped download will probably take longer than just downloading it). At any rate, the biggest improvement here is that Android bindings will only be compiled if there's some change in the Android directories; up to now it was always being compiled, no matter what. The rest of the changes are in the commit messages, mainly reducing verbiage and fixing a typo.
=> Minor improvements in the build of android bindings

platform/ios/PolyPodApp/PodApi/PolyOut/FS/PolyOut+FS.swift
Again a quick fix for removeArchive not working (us not being able to remove files) in ios due to ids. 
It would be lovely if someone could get onto https://jira.polypoly.eu/browse/PROD4POD-1613.
=> Fix wrong path id

build/npm.js, feature-utils/poly-look/package-lock.json
I was getting errors when building in the new laptop, and it was our old friend the prefer-offline installation. So first I upgraded pretty-format to basically have a single version of it in package-lock, and eventually fixed the whole thing to a state where it should have been some time ago
=> Really fix the default installation mode

.github/workflows/codeql-analysis.yml
v1 is being deprecated according to https://github.blog/changelog/2022-04-27-code-scanning-deprecation-of-codeql-action-v1/
=> [⬆] Upgrade CodeQL actions to v2

platform/core/PolyPodCoreSwift/Sources/PolyPodCoreSwift/Core.swift, platform/core/PolyPodCoreSwift/Sources/PolyPodCoreSwift/FBObject.swift, platform/core/PolyPodCoreSwift/Sources/PolyPodCoreSwift/FlatbObject.swift, platform/ios/PolyPodApp/Features/Feature.swift
Instead of deallocating the bytes after  the root level flatbuffer is extracted, deallocate the bytes after the whole model is dropped. The main issues is that the FlatBuffer model does no own the bytes as per [docs](https://github.com/google/flatbuffers/blob/967df08b1dbddc62f867464c2e0d58d8027438ad/swift/Sources/FlatBuffers/ByteBuffer.swift#L170) 
What was done:
- Encapsulate the flatbuffer model and its backing bytes in `FBObject` class. When `FBObject` is deallocated the bytes will be freed.
=> Fix Core bytes memory management

feature-utils/poly-look/src/react-components/infographic/infographic.jsx, features/google/src/locales/de/infoScreens/commonInfoScreen.json
The texts in the infographic weren't translated because the selector was too broad and when there are multiple svgs in a page there was no guarantee that you would get the one you wanted.
=> fix(poly-look) - prod4pod-1634  fix infographic text replacement

features/google/src/model/importers/access-log-importer.js, features/google/src/views/explore/explore.jsx
Quick fix: because all files get two entries (macOS directory and normal directory), the importer was returning an array of two arrays. This slipped as the dataGroups was not taking into account the accesslog, now that it does, the problem became apparent.
=> Fix accesslog import

features/google/src/views/overview/overview.jsx
This basically catches the error and proposes a default. A better fix would try and see what's the real attribute value in that case.
=> Fix invalid time value

features/google/src/model/analyses/analyses.js, features/google/src/model/analyses/analysisKeys.js, features/google/src/model/analyses/ministories/report-metadata.js, features/google/src/views/ministories/ministories.js, features/google/src/views/ministories/reportMetadata.jsx, features/google/src/views/ministories/reports.js
Metadata is going to appear *here* **and** at the bottom of the other ministory; I've kinda figured out how to eliminate any of them so I admit any suggestions over that.
It's essentially copypasta from facebook, so we might want to factor that out; only difference is that report language is not used in Google.
=> [Feat] {PROD4POD-1648} Add metadata ministory

platform/android/app/src/main/assets/container/container.js, platform/ios/PolyPodApp/PodApi/messagePort.js, platform/ios/PolyPodApp/PodApi/polyNav.js
I've used localhost, which seems reasonable, and no reference to the protocol; this will make CodeQL happy and add a reasonable layer of security
This takes care of [ŧhis warning](https://github.com/polypoly-eu/polyPod/security/code-scanning/36), as well as [this one](https://github.com/polypoly-eu/polyPod/security/code-scanning/34) and [this one](https://github.com/polypoly-eu/polyPod/security/code-scanning/35)
=> [🐛] Check origin to get rid of warning

.github/workflows/js-and-android-test.yml
Since the old GitHub Action path has been disabled, we need to bring this here to avoid failures.
=> [Bug] Bring new hash here

features/google/src/model/analyses/ministories/report-metadata.js, features/google/src/views/ministories/reportMetadata.jsx
If the data includes «fake», it will be labeled as an example. This will be shown this way:
=> [Feat] {PROD4POD-1655} Identify examples in reports

features/google/src/views/ministories/reportMetadata.jsx
Since the workflow was not working, it was showing green when it should not. This fixes it.
=> :green_heart: Fix CI

features/google/src/model/analyses/ministories/report-metadata.js, features/google/src/views/ministories/reportMetadata.jsx, platform/android/app/src/main/AndroidManifest.xml, platform/android/app/src/main/java/coop/polypoly/polypod/PodUnlockActivity.kt, platform/android/app/src/main/kotlin/coop/polypoly/polypod/Authentication.kt, platform/android/app/src/main/kotlin/coop/polypoly/polypod/MainActivity.kt, platform/android/app/src/main/res/layout/activity_pod_unlock.xml, platform/ios/PolyPodApp/PolyPod.xcodeproj/project.pbxproj, platform/ios/PolyPodApp/PolyPod/ContentView.swift, platform/ios/PolyPodApp/PolyPod/OnboardingView.swift, platform/ios/PolyPodApp/PolyPod/SharedUIComponents.swift, platform/ios/PolyPodApp/PolyPod/UnlockPolyPod.swift
Instead of "relentless" authentication add a simple unlock screen.
The original issues was that the app was left in limbo state when User did not log in properly. The root cause is that biometric prompt can be cancelled at any time by the user or by the system(for example when moving the app to background), this cannot be fixed reliably with just some code hacks.
What was done:
- Add a simple Unlock Pod screen, UI could be further improved with next iterations.
- If biometric prompt is dismissed for whatever reason, unlock screen is shown and user can tap on the button to try to unlock the Pod again.
=> PROD4POD-1656 - Add pod unlock screen

platform/android/app/src/main/java/coop/polypoly/polypod/PodUnlockActivity.kt, platform/android/app/src/main/kotlin/coop/polypoly/polypod/Authentication.kt, platform/android/app/src/main/kotlin/coop/polypoly/polypod/OnboardingActivity.kt, platform/android/app/src/main/kotlin/coop/polypoly/polypod/settings/MainFragment.kt
Following updated diagram flows of authentication https://wiki.polypoly.eu/display/POLYPOD/system+lock+for+polyPod 
we correct the texts shown to the user when they are prompted to the authentication setting.
We simplified the cases, so now show:
- "Login to your polyPod" text (aka `auth_*` texts) when on onboarding, and when polyPod starts over.
- "Authenticate to continue"  text (aka `reauth_*`  texts) when toggle button is pressed, independently of the value changed.
For this we used two different flag variables:  `showAuthTexts` for the UI texts and `newBiometricState` (previously named `newStatus`) to not break the current security flow and make sure UI is as requested.
Note:
tested by security @L-E  🟢
=> Fix Authentication screen texts in Android

platform/android/app/src/main/kotlin/coop/polypoly/polypod/polyOut/PolyOut.kt
Setting the file system here will replace the entire file system only with the files that the feature can access aka deleting the google import when opening fbImport
More than co-authored by @alexandrosFarhat
=> Do not set file system to prevent file deletion on opening app - bug fix

platform/ios/PolyPodApp/Extensions/ColorExtensions.swift, platform/ios/PolyPodApp/Extensions/UIColorExtensions.swift, platform/ios/PolyPodApp/PolyPod/FilePicker.swift
Fix warning for method `[UIDocumentPickerViewController - 'init(documentTypes:in:)']` which is deprecated from iOS 14, so need support for both iOS 14 and later. And iOS 13 and earlier.
Drop code support for <ios14 that was marked with `#available` previously
=> fix warning for deprecated `UIDocumentPickerViewController.init()` in ios14

features/facebookImport/src/components/importExplanationExpandable/importExplanationExpandable.css
To address the [PROD4POD-1644 Expansion panel head bars are not correct in Google Importer](https://jira.polypoly.eu/browse/PROD4POD-1644), I had to changed Facebook import view - margins were duplicated due to the implementation of Screen component.
This ticket was under [PROD4POD-1570 Release polyPod 1.6 with Google Feature](https://jira.polypoly.eu/browse/PROD4POD-1570) but I'm having doubts about the priority of this due to feature freeze. 🤔
=> PROD4POD-1644/Fix Facebook import view

platform/android/app/src/main/kotlin/coop/polypoly/polypod/features/Feature.kt, platform/android/app/src/main/kotlin/coop/polypoly/polypod/homescreen/HomeScreenFragment.kt, platform/android/app/src/main/kotlin/coop/polypoly/polypod/homescreen/HomeScreenLayouts.kt, platform/android/app/src/main/kotlin/coop/polypoly/polypod/homescreen/HomeScreenTiles.kt, platform/android/app/src/main/kotlin/coop/polypoly/polypod/homescreen/HomeScreenViewModel.kt
Add borders specs (width, color) on the home screen tiles.
`borderColor` is specified in the manifest
`borderWidth` is part of the layout, defined in PolyStyle
=> [android] Add borders on home screen tiles - PROD4POD-1697

platform/android/app/src/main/assets/container/container.js, platform/ios/PolyPodApp/PodApi/messagePort.js, platform/ios/PolyPodApp/PodApi/polyNav.js
On Android it happens that Importer features are loading due to this change(Loading spinner is shown indefinitely).
From debugging allowing I saw that `event` object does not contain the origin property.
Until we have a good approach on how to fix this, simply revert the change so importers are loading again.
=> Revert origin check for now

platform/feature-api/api/pod-api/package-lock.json, platform/podjs/package-lock.json
Although all code has been removed, and uninstalled from dependencies, there's an error in `npm uninstall` that leaves packages in the package-lock.json, unremovable if it's not by hand. There are still remains of this in all features, however, these lockfiles change more frequently and they will probably be eliminated next time they're updated. That does not happen with these (although one of them is going to be eliminated when #794 lands) so that limits the scope of this PR.
=> [⚰] {PROD4POD-632} fetch-spec redux

.github/workflows/js-and-android-test.yml
Re-sets the hash to the new value, to make this workflow work again
=> Set the new hash in dorny/path-filters

.github/workflows/js-and-android-test.yml
This, in combination to configuration to avoid merge when tests fail, will avoid future problems that arise when a merged PR fails tests. It will have to be combined with a change in configuration that will prevent merge when tests fail.
=> Adds a test when merged

.github/workflows/js-and-android-test.yml, package-lock.json, platform/core/README.md
Looking to avoid errors such as [this one](https://github.com/polypoly-eu/polyPod/runs/7088879088?check_suite_focus=true)
Essentially, it adds the root `node_modules` to the directories that are cached. The rest have been make to trigger builds, or to change stuff that was probably wrong, or to tweak a bit the description of actions or documentation.
=> [Fix] Tweaks paths to trigger install when needed

feature-utils/poly-look/package-lock.json
... and failing. The problem is that I think snyk is not able to work properly on symlinked directories in the same project. That's not the case here; in this case, `fsevents` is an optional dependency in all modules where it's included, and I think it's simply not installed. At any rate, syncing lockfiles from time to time might be a good thing; what this actually does is to include in `package-lock.json` the `silly-i18n` dep, which was empty for some reason.
=> {PROD4POD-1505} Sync to make fsevents current... and failing.

features/google/src/model/importers/utils/lang-constants.js
It's very likely that to avoid fs problems, file names do not use canonical forms. Or it might something else, I really don't know. This passes to canonical form, which should make the comparison work.
=> Use a normalized canonical form to check the path

platform/ios/PolyPodApp/PodApi/PolyOut/FS/PolyOut+FS.swift
Performed the correct check.
This part of the code was refactored with https://github.com/polypoly-eu/polyPod/pull/1011/files.
The breaking change was refactoring `url != ""` to `url.isEmpty`.
P.S. We really need to have some tests asserting that Features are actually loading, this seems to be very fragile. This is the second time in a week I had to hunt down the root cause of the issue, spent like 4 hours in total just doing that...
=> Fix importer features not loading on iOS

features/polyExplorer/src/locales/en/dataTypeBubble.json
It's only in the `en` locale, it's not really used.
=> [⚰] {PROD4POD-1730} Eliminate unused/inconsistent translation files

platform/feature-api/api/rollup.config.js, platform/podjs/rollup.config.js
Instead of exporting it piecemeal, let's use `rollup`s tree shaking to bundle only whatever is actually needed
Eliminated also the cjs exported by pod, which is just impossible and possibly not used.
This is a follow-up to #794, which reorganized rollup for 5 modules in a single one... But that was causing problems for #989, namely problems with pod.js tests due to the incorporation of node.js files (like `buffer` in the bundle). This may or may not have caused general problems, but certainly works better now.
=> [♻] Reorganizes rollup in api to export the correct formats

dev-utils/poly-cli/src/templates/package.js
Either we add dummy tests, or we simply eliminate this. `build.js` will try to run a test if the script is present, so better to eliminate it
=> We don't need failing tests since they will make PRs fail

platform/podjs/cypress.json
Occasionally, [pod.js tests time out](https://github.com/polypoly-eu/polyPod/runs/7216821167?check_suite_focus=true) since some commands take a lot of time (4 seconds, sometimes even more)
> It *always* times out locally in my desktop, so this might or might not hide a bug
However, to avoid these timeouts we will just increase the time out for the time being. Maybe investigate the matter further down the line. I have tripled the [default  value](https://docs.cypress.io/guides/references/legacy-configuration#Timeouts). Such a big timeout is probably not needed, but if it does not work, it will not work anyway, and will give us some leeway.
=> ⌛ Eliminate test failures due to timeouts in pod.js

.github/workflows/daily-instrumentation-test.yml, .github/workflows/ios-test.yml
Android tests take place in the MacOS runner, which takes a lot and is quite unreliable, and adding insult to injury, it might take up to 4 minutes to set up Java, bringing everything to just south (and sometimes north) of 40 minutes [like here](https://github.com/polypoly-eu/polyPod/runs/7216940598?check_suite_focus=true).
All in all, running those instrumentation tests every time does not make a lot of sense. Besides, I don't think they've ever failed, maybe because they will only catch very catastrophic errors. So this PR splits them in two different github actions, one that will just test iOS (that can't be helped), and another scheduled to be triggered every afternoon that will run the instrumentation tests. We can still run them manually if we want, but we will not have to wait 20 …
=> Split iOS tests

.github/workflows/js-and-android-test.yml, platform/android/app/build.gradle, platform/android/app/src/main/kotlin/coop/polypoly/polypod/FeatureContainer.kt, platform/android/app/src/main/kotlin/coop/polypoly/polypod/PodApi.kt, platform/android/app/src/main/kotlin/coop/polypoly/polypod/endpoint/Endpoint.kt, platform/android/app/src/main/kotlin/coop/polypoly/polypod/network/Network.kt
Several things done here:
* :arrow_up: Upgrade `java-setup` to latest version. Old version was taking a long time in the Ubuntu runner, a looooong time in the iOS runner.
* :arrow_double_up: Upgrade `robolectric` to try and avoid reflection warnings. It was several minors behind anyway.
* :rotating_light: Fixing some linting errors that were revealed by the gradle build (not by the Kotlin linter), mainly to trigger new builds.
* :gear: Set up a cache for gradle
=> [♻] Improve android workflows by avoiding warnings

platform/ios/PolyPodApp/PolyPod/SettingsView.swift
Fix of the bug 🐛 having translation strings instead of real text on the titles of SettingsView page on iOS devices.
This bug was introduced after the upgrade to iOs 14, with the use of `() -> String in` inside the `Τext` οbject.
To fix this, we add an `extension` of `Section`, so we compute property of title instead of having an ugly switch on the view. we then can call directly `activeSection.title()`
=> fix translation strings bug on settings view - ios

platform/ios/PolyPodApp/PolyPod/Authentication.swift, platform/ios/PolyPodApp/PolyPod/ContentView.swift, platform/ios/PolyPodApp/PolyPod/SettingsView.swift
Τo reflect the diagram https://wiki.polypoly.eu/display/POLYPOD/system+lock+for+polyPod of the authentication as requested by security, we remove the show of `onboardingView` when the settings are triggered, case 2.0 of diagram, (`securityReminderState()`)  and show instead directly the main screen with the features list.
(rest of changes are minor linting fixes 🧹 )
=> fix - remove onboarding screen on settings triggering in iOS - PROD4POD-1663

features/lexicon/.gitignore
Why isn't just all public ignored here?
=> Ignore all public in lexicon

feature-utils/poly-look/src/react-components/overlays/sideSheet.css, feature-utils/poly-look/src/react-components/overlays/sideSheet.jsx
By removing max-width we ensure that when we'll operate on larger viewports the htrt screens using this component will function correctly.
=> fix: prod4pod-1741 - removed max-width from SideSheet

platform/android/app/src/main/kotlin/coop/polypoly/polypod/OnboardingActivity.kt
🐞 Change the text used during onboarding to be "Authenticate to continue". 
just need to call the `Authentication.setUp` with `false` `showAuthTexts` param so we show the `reauth` texts when on onboarding.
=> fix: show reauth texts on onboarding screen [android] - PROD4POD-1698

platform/android/app/src/androidTest/kotlin/coop/polypoly/polypod/UpdateNotificationTest.kt, platform/android/app/src/main/kotlin/coop/polypoly/polypod/Authentication.kt, platform/android/app/src/main/kotlin/coop/polypoly/polypod/MainActivity.kt, platform/android/app/src/main/kotlin/coop/polypoly/polypod/OnboardingActivity.kt, platform/android/app/src/main/kotlin/coop/polypoly/polypod/Preferences.kt
🔧 fixes security onboarding screen being shown after just disabling authentication
we introduce a new key for `userConfiguredAuth` to mark that user has successfully configured authentication on onboarding prompt
and distinguish from the option "do not ask anymore".
setting this new value makes it possible to check properly and not showing anymore the onboarding when the configuration is off.
+ some more readable namings on vars/functions, and other small nits refactors on the way
co-authored & tested by 🧪 @GhenadiePusca
=> fix - authentication flow in Android - [PROD4POD-1663]

feature-utils/poly-look/storybook/package-lock.json
But this revealed even more vulnerabilities. At least svelte has been upgraded or eliminated, taking care of [this](https://github.com/polypoly-eu/polyPod/security/dependabot/114) (possibly)
=> Audited and fixed some vulnerabilities

.github/workflows/ios-test.yml
The timeout has happened in #1076, so it's likely it's not triggered here. Anway, it's a bit over the brink, so maybe an upgrade of the cache code will fix it; among other things, it changes node from version 12 to version 16 (although, for some reason, that part is written in Csharp?).
Anyway, if this does not work, there are no easy alternatives. [This PR is waiting to be vetted](https://github.com/actions/runner/pull/1844), so I'm afraid we will have to disconnect the cache (it's very likely it's not making any good in this specific runner, too)
Eliminate cache. Best case scenario, we were obtaining marginal gains; installing modules took anywhere from 2 minutes to 6 minutes; but downloading and uncompressing the cache never took less than 4 minutes. So even in the best case scenario …
=> [🐛] {PROD4POD-1779} Try to fix lockfile-hashing timeout

platform/android/polyOut/build.gradle
Just upgrade to advised version
=> [🐛] {PROD4POD-1747} Upgrade to avoid kotlin "improper locking" bug

.github/workflows/js-and-android-test.yml, package-lock.json, platform/feature-api/api/.gitignore
Well, this was trying to fix a build error, but then I realized there was nothing wrong with our build process, but there was something absolutely wrong with the [cache that caused that error](https://github.com/polypoly-eu/polyPod/runs/7444510299?check_suite_focus=true)
Complicated to see why that was generated, since you cannot search for cache keys. I'll try to have a look anyway, but outside this  PR. Two sets of changes apparently unrelated, but needed
* Upgrade one module to trigger cache regeneration
* Elimination of unneeded entries from one `.gitignore`; these were boilerplate JS entries, and some of them were repeated. Not a big deal if we customize the .gitgnore file to our own situation.
=> Regenerate cache to make it grow bigger than 22 bytes

platform/ios/PolyPodApp/PolyPodTests/PolyOutTests.swift, platform/ios/PolyPodApp/PolyPodUITests/UpdateNotificationTest.swift
Basically doubling timeouts where they were happening.
=> [♻] {PROD4POD-1618} Avoid swift timeouts

.github/pull_request_template.md
Following discussion in https://wiki.polypoly.eu/display/POLYPOD/Proposal+for+Pull-Requests+template 
this is the  template for Github PRs as the merged outcome out of the preferences of the team.
So, when this will be merged, when we create a new pull request, we will see the template content automatically loaded into the description field.
We will only require to fill-in the requested information and 🧹 delete the comments or image placeholders (as here ⏬ ) from the message. 
For the whole dev experience as discussed in the wiki page, we need to accompany this change with the installation of this add-on https://github.com/zachwhaley/squashed-merge-message on our browsers that copies the PR's description into the squash&merge commit's message, so we will keep all the needed information …
=> add GitHub pull-request template

platform/feature-api/api/package-lock.json, platform/feature-api/api/package.json, platform/feature-api/api/src/pod-api/index.ts, platform/feature-api/api/src/pod-api/tests/uri.test.ts, platform/feature-api/api/src/pod-api/uri.ts, platform/podjs/src/browserPod.ts
We've been working in a rather ad-hoc way with polypod URIs, for instance in browserPod. The main intention here is to bring them to spec and have an uniform handling of them.
This new class has been...
:no_entry_sign:  This is a blocker for finishing #989, which is a blocker for #977. 
Possibly in scope: changing `destUrl` as a `string` to a PolyPodUri. This would be more type-safe. There are not so many invocations, however, and that would need a deeper refactoring of the interface and a whole lot of functions up and down the polyPod and apps.
=> ♻ Work with polypod URIs

.github/pull_request_template.md
Correcting some markdowns on the PR template
mainly to trigger a PR to display to team members how the template on GitHub will appear
and that the description is copied into the `squash merge` commit message.
not-applied-here 
not-applied-here
(above sections if are empty can be deleted in proper PRs - leaving them here to display the way the template will be)
♥️ Thank you!
=> fix markdown on the PR template

.eslintrc.cjs, build/index.js, feature-utils/poly-look/storybook/web-dev-server.config.mjs, features/facebookImport/rollup.config.mjs
While doing #1090, I realized `.mjs` code, which was introduced for rollup configurations in #903, was not being linted. For two reasons:
1. That extension is not linted by default
2. They were all `*.config.*` files which were also excluded explicitly.
I don't really see a good reason for this to happen any more; rollup config files have become complex enough for them to be linted along the rest of the files. This is what this PR does; it also fixes linting errors found (which will supersede #1090, BTW, at least in the state it's in this draft)
♥️ Thank you!
=> [♻] eslint should also check mjs

feature-utils/poly-look/package-lock.json, feature-utils/poly-look/package.json, features/google/package-lock.json, features/google/package.json
This d3-color version should take care of the snyk warning, but I don't think our code was really affected. Anyway, keeping up to date with some modules as in this case, which is used extensively in visualization, is probably a good thing.
Upgrades d3 and d3-color in two submodules. Only the google feature had an affected `d3-color`, but this way we uniformize the versions we're using in both modules.
Although this is simply a general heath fix, not really a vulnerability that affected our products.
♥️ Thank you!
=> [🐛] {PROD4POD-1790} Upgraded d3 + d3-color

platform/podjs/src/browserPod.ts
While doing #989, these linting errors were revealed by the IDE.
- Documentation error file → manifest
- Casting needs an intermediate `unknown`
- Deprecated atributes
♥️ Thank you!
=> [:rotating_light:] Minor refactoring of browserPod.ts to eliminate IDE linting warnings

.github/workflows/codeql-analysis.yml, .github/workflows/daily-instrumentation-test.yml, .github/workflows/js-and-android-test.yml, platform/core/Makefile, platform/core/README.md
GH environment released NDK r25 support -> https://github.com/actions/virtual-environments/releases. 
What has been done:
=> Adapt to NDK r25

platform/ios/PolyPodApp/PolyPodUITests/UpdateNotificationTest.swift
The iOS notification tests fail for me quite consistently locally, the
same notification shows up twice even though it was previously closed.
Adding a `sleep` after the `tap` of the close button seems to fix it.
There's no Jira issue.
=> Fix iOS update notification tests

platform/android/app/build.gradle
At the moment, every time we deploy the tests, the build process will
copy over the feature named "test" to the device.
Now that we're always bundling - but not displaying - it, we can just
add a preference for forcing it to show up, and execute the tests in
it that way, so we don't need this logic anymore. It's sometimes
causing trouble when trying to run the tests - happened to me again
just now - and it's not worth debugging if we don't need it.
Related to PROD4POD-1721.
=> Eliminate copying the test feature to the device

platform/feature-api/api/src/pod-api/api.ts, platform/feature-api/api/src/pod-api/default.ts, platform/podjs/package-lock.json, platform/podjs/package.json, platform/podjs/src/browserPod.ts
@RichardSto I had a go at persisting the Oxigraph store in IndexedDB. With this PR, I'm populating the store using the `Store#load` method during intilization, and call the `Store#dump` method and write the result into IndexedDB  on every call to `PolyIn#add` and `PolyIn#delete`. Multiple calls during the same event loop cycle only cause one write to IndexedDB.
Any reason you exposed Oxigraph's store in the public API? I made it private with the changes here since otherwise we cannot make sure that all write operations are synced to IndexedDB.
=> Sync Oxigraph store into IndexedDB

platform/android/app/src/main/kotlin/coop/polypoly/polypod/homescreen/HomeScreenViewModel.kt
Made the change to not crash the Android app if thumbnail is missing.
=> Android: Do not crash the app when thumbnail is missing

features/example/src/index.jsx, features/test/cypress/integration/tests.spec.js, features/test/src/index.html, features/test/src/test.ts, platform/feature-api/api/src/rdf-spec/gen.ts, platform/feature-api/api/src/rdf/index.ts, platform/podjs/src/browserPod.ts
@RichardSto I had to make following changes to make the tests pass with Oxigraph:
1. The tests for the `example` feature failed because they relied on `JSON.stringify(term)` producing a string that conatins the value of the respective term. However, since Oxigraph's objects are managed by WASM the only property on the object that isn't a getter is `ptr` which holds the relative memory address. So I had to replace `JSON.stringify(term)` with `term.toString()`.
2. Since you changed the API from `polyIn.add(...quads)` to `polyIn.add(quad)`, I had to remove the test testing that `polyIn.add` can be called with no arguments.
3. The `test` feature was creating named nodes to test the API with from an empty string. But Oxigraph is more strict than the previous implementation, and throws an error …
=> Make tests pass with oxigraph

platform/podjs/rollup.config.js
Circular dependency warnings create noise in the build, obscure other, more important issues. In general, we have suppressed them.
We're just following the same pattern here. Warning event is detected, and eliminated in the case it's related to fast-check, which is what's causing it (not our code)
♥️ Thank you!
=> [Fix] Eliminates warning for circular dependencies

platform/feature-api/api/rollup.config.js
This addresses rollup warnings that were showing up in the build, such as this one:
This adds the `uuid` to the list of external dependencies. Avoids that warning, also prevents the bundled code from failing when embedded in a page.
♥️ Thank you!
=> [Fix] Address build warnings by adding as external dep

platform/podjs/src/browserPod.ts
After #1137, this was left and was causing a warning. It's been eliminated.
♥️ Thank you!
=> Eliminates code that's no longer needed

platform/podjs/rollup.config.js
The code has been DRYed. I've created a better regex, because the previous one, as indicated by @snoack in #1126, was eliminating every warning.
This one takes care of the two kinds of warnings that were there
There are a couple of places where the same pattern was used to suppress warnings.  If this new code is OK for everyone (it was already used in a couple of places), I can also refactor those within this same PR.
♥️ Thank you!
=> [🐛] Suppress only the warnings we're interested in

feature-utils/poly-look/storybook/.storybook/react/preview.js, feature-utils/poly-look/storybook/.storybook/react/preview.jsx, feature-utils/poly-look/storybook/stories/react-components/buttons/icon.stories.js, feature-utils/poly-look/storybook/stories/react-components/buttons/polyButton.stories.js, feature-utils/poly-look/storybook/stories/react-components/demo.css, feature-utils/poly-look/storybook/stories/react-components/infographic.stories.js, feature-utils/poly-look/storybook/stories/react-components/legend.stories.js, feature-utils/poly-look/storybook/stories/react-components/overlays/sideSheet.stories.js, feature-utils/poly-look/storybook/stories/react-components/overlays/sideSwiper.stories.js, feature-utils/poly-look/storybook/stories/react-components/slideshow.stories.js, feature-utils/poly-look/storybook/stories/react-components/tooltip.stories.js
Since we are in the process of improving our theming and looking at better usage of design tokens, this PR is supporting that effort by adding theming support to Storybook.
The main changes are in `preview.jsx` and they were done by adapting this [blog post](https://storybook.js.org/blog/how-to-add-a-theme-switcher-to-storybook/) to our needs.
We now have the possibility or toggling the themes directly from the toolbar without having to do any more manual wiring ourselves.
=> feat: prod4pod-1829 - add theming support to Storybook

dev-utils/poly-cli/src/static/templates/index.jsx, dev-utils/poly-cli/src/static/templates/preview/index.jsx, feature-utils/poly-look/src/css/layout.css, features/amazonDataImporterPreview/src/index.jsx, features/companyDataCleanerPreview/src/index.jsx, features/cooperativeMembershipPreview/src/index.jsx, features/featureStorePreview/src/index.jsx, features/gdprDataImporterPreview/src/index.jsx, features/netflixDataImporterPreview/src/index.jsx, features/polyTalkPreview/src/index.jsx, features/polypediaPreview/src/index.jsx, features/polypolyMembership/src/index.jsx, features/polypolyMembershipPreview/src/index.jsx
Every time we implemented the `Screen` component in a new feature, it covered the nav bar on the top. We have been fixing it in each feature, but it happened every time that we created a new one. 
In order to create a more permanent solution, I have created a `feature-container` class in `poly-look` and added it to the "feature" and "preview-feature" templates in `poly-cli`. This fixes the problem for potential new features.
I have also added/replaced that class for the current features that didn't have it yet.
[How it looked like.](https://jira.polypoly.eu/secure/attachment/14665/How%20it%20looks%202.png)
[How it looks now.](https://jira.polypoly.eu/secure/attachment/14663/How%20it%20should%20look%202.png)
=> PROD4POD-1884 - Fix Screen component overlap

platform/feature-api/api/src/pod-api/mock-store.ts
Since they must adhere to a specific interface, it seems the most sensible thing to just disable the warning
♥️ Thank you!
=> :rotating_light: Address linting warnings

feature-utils/poly-look/src/css/design-system-tokens/spacing.css, feature-utils/poly-look/src/css/icons.css, feature-utils/poly-look/src/css/index.js, feature-utils/poly-look/src/react-components/buttons/polyButton.css, feature-utils/poly-look/src/react-components/buttons/polyButton.jsx, feature-utils/poly-look/storybook/.storybook/react/preview.jsx, feature-utils/poly-look/storybook/stories/react-components/buttons/polyButton.stories.js, feature-utils/poly-look/storybook/stories/react-components/demo.css, feature-utils/poly-look/test/react-components/buttons/polyButton.test.js
This PR adds icon(s) to the PollyButton component.
While in practice we would only use one of the icon options, there are no code restrictions for that.
Initially I had planned for `iconLeft` and `iconRight` to accept either a string representing a path  or a component as prop (current implementation) and let the button decide how to render that.
After some consideration to theming I've decided to get rid of the `img` support and keep only the component as prop approach. That's done to encourage the inline SVG approach to icons.
I haven't added any css rule for the fill because I'm not sure how the icons would look like, so I'll leave it up to the dev using this component to decide.
In the examples below, the square is an inline SVG with fill set to `currentColor`. For theming that would …
=> feat(polyLook) - prod4pod-1879 add icon options to PolyButton

platform/ios/PolyPodApp/PolyPodTests/PolyOutTests.swift
Increase timeout, which recent shared code seems to need
[This error](https://github.com/polypoly-eu/polyPod/runs/8299236692?check_suite_focus=true)
No one is interested in this, but this minimal thing was done integrally on my Mac Air, since the desktop crashed and I had the Mac handy, readied for the classes.
♥️ Thank you!
=> [Fix] Increase timeout

features/facebookImport/src/locales/de/explore.json, features/facebookImport/src/locales/en/explore.json, features/facebookImport/src/views/explore/explore.jsx, features/facebookImport/src/views/ministories/dataImportingStatus.jsx, features/facebookImport/src/views/ministories/missingKnownJsonFiles.jsx, features/facebookImport/src/views/ministories/offFacebookEventsTypes.jsx, features/facebookImport/src/views/ministories/reportMetadata.jsx, features/facebookImport/src/views/ministories/unknownTopLevelFolders.jsx
For a variety of reasons, it can happen that there are no analyses in
the account object. With this change, we deal with that in two ways:
1. We show a message to the user when no stories could be rendered.
2. The report works even if there aren't any (report) analyses.
=> Deal with missing analyses

features/facebookImport/test/mocks/zipfile-mock.js
I bumped into this while refactoring facebookImport.
Changed one instance of unescape. The other one, in `jsonStringifyWithUtfEscape` is tricky, since it's apparently relying on some undocumented feature.
The other one is tricky, since it's apparently relying on some undocumented feature. ~But I need to look into it, since I'm not totally sure we still need it after #1158 ~
Well, it's used to generate mock JSON files with the same weird encoding that Facebook has. After #1158, we might need to invert the `decode` function we added there. Might still be in scope.
♥️ Thank you!
=> [♻] `unescape` is deprecated

features/facebookImport/rollup.config.mjs, features/facebookImport/src/components/buttons/infoButton/infoButton.jsx, features/facebookImport/src/components/routeButton.jsx, features/facebookImport/src/context/facebook-context.jsx, features/facebookImport/src/facebookImporter.jsx, features/facebookImport/src/popUps/baseInfoPopUp/baseInfoPopUp.jsx, features/facebookImport/src/views/explore/explore.jsx, features/facebookImport/src/views/import/import.jsx, features/facebookImport/src/views/report/report.jsx, features/google/rollup.config.mjs
I think this clashes with poly-import, which does something completely different and then we have google-context. So it only makes sense to have facebook-context
=> Rename importercontext to facebookcontext

platform/ios/PolyPodApp/PolyPod/Info.plist
Not only they were not used, where they were used was deleted in #952
♥️ Thank you!
=> [🐛] {PROD2POD-1600} Deletes location trackers

platform/android/app/src/main/AndroidManifest.xml
Change exported to false so that it can't be used from other applications. This is tentative, since it might be used from the integrations tests,
Essentially follows suggestion by setting exported to `false`
♥️ Thank you!
=> [🐛] PROD4POD-1752

.github/workflows/ios-test.yml, .github/workflows/js-and-android-test.yml
Now, additionally to the tests that are run when a push happens, it runs additional tests when certain things happen in a PR. This is not really necessary, since PRs follow the same code path that would follow the latest commit. Duplicated tests can be useful to detect flappers, but this specific test does not have a lot of them. Will leave just one duplicated test to take care of that, and that's that.
♥️ Thank you!
=> Tweak GitHub Actions

features/facebookImport/src/views/explore/details.jsx, features/facebookImport/src/views/explore/explore.jsx
Bug introduced here https://github.com/polypoly-eu/polyPod/commit/e83ebe6f5fce4580deddd0e4fba16ddac25d59a4
`ministory.constructor.name` is a string while it expects a `storyClass`
Now it gets the actual story so it doesn't need to be generated twice anymore
=> Fix bug when clicking details by changing way story is transferred via state

feature-utils/poly-look/package-lock.json, feature-utils/poly-look/package.json, features/google/package-lock.json, features/google/package.json, features/polyExplorer/package-lock.json, features/polyExplorer/package.json
Tries to quell [these vulnerabilities](https://github.com/polypoly-eu/polyPod/security/dependabot/136) by upgrading d3, which was a couple of minors behind anyway. As usual, not something that could affect us, since it's no user-facing code, but upgrading is good and eliminates annoying warnings.
♥️ Thank you!
=> [Fix] d3 color security vulnerabilities

platform/android/app/src/main/kotlin/coop/polypoly/polypod/homescreen/HomeScreenContainers.kt, platform/android/app/src/main/kotlin/coop/polypoly/polypod/network/Network.kt
In tests or builds such as [this one](https://github.com/polypoly-eu/polyPod/actions/runs/3088056402/jobs/4994093066) there are a number of warnings (which also show up in Android Studio) that are not caught by the linter
Address warnings as well as possible
* Rename shadowed variables
* Eliminate unreachable code
> Refactoring deprecated code might be in scope, but needs a bit of research
♥️ Thank you!
=> [♻] Address deprecations and other warnings in Kotlin

.github/workflows/android-test.yml, .github/workflows/codeql-analysis.yml, .github/workflows/ios-test.yml, .github/workflows/js-and-android-test.yml, .github/workflows/ktlint.yaml, .github/workflows/rust_kernel_tests.yml, .github/workflows/swiftlint.yaml
To avoid trouble with loss of support for node v12. It was causing warnings here and there,
♥️ Thank you!
=> [:arrow_up:] Upgrade `actions/checkout` to v3

feature-utils/poly-import/src/storage.js, feature-utils/poly-look/src/react-components/contexts/poly-import.jsx
Assigning a value to an attribute violated encapsulation, which is easy to do in JS, but still. This is a cleaner API, with a private `changeListener` which is assigned when the object is built.
Still cleaning up and refactoring the importer, looking at improving coverage. Related to #1209 and #1204, but wanted it to be considered on its own.
Also it's a change of API, which is better if considered on its own.
♥️ Thank you!
=> [:recycle:] `changeListener` moved to the constructor

feature-utils/poly-look/src/react-components/filterChips.jsx, features/polyExplorer/src/components/embeddedSankey/embeddedSankey.jsx
Fixes: https://jira.polypoly.eu/browse/PROD4POD-1945
The defaultChipsProp needs to update the activeChips state. The update was not done correctly. 
You need a ref to keep the initial active chips, and then an effect to change that ref, and watch for changes to the prop.
=> [PROD4POD-1945] FIX: Too many rerenders 

platform/android/app/src/main/kotlin/coop/polypoly/polypod/MainActivity.kt, platform/android/app/src/main/res/xml/network_security_config.xml
Fixes 
`Exception java.lang.RuntimeException: Unable to instantiate application android.app.Application: java.lang.RuntimeException: Failed to parse XML configuration from network_security_config
at android.app.LoadedApk.makeApplication (LoadedApk.java:1268)
at android.app.ActivityThread.handleBindApplication (ActivityThread.java:6690)
at android.app.ActivityThread.access$1300 (ActivityThread.java:237)
at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1913)
at android.os.Handler.dispatchMessage (Handler.java:106)
at android.os.Looper.loop (Looper.java:223)
at android.app.ActivityThread.main (ActivityThread.java:7664)
at java.lang.reflect.Method.invoke
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:592)
at …
=> Fix android gradle

feature-utils/poly-import/utils/zipfile-mock.js
Again, this was found wanting for #1218. This coupling was probably not needed, so that all information for an entry occurs in the entry itself, and it does not need to be handled by the hosting zipFile. Since this is a Mock, we don't really need more than that.
Might include some tests, and additional spin-off of all ZipMockFile methods that create Entries.
♥️ Thank you!
=> [:recycle:] Eliminate unneeded coupling with zipFile :coffin:

.github/workflows/android-test.yml, .github/workflows/js-and-android-test.yml
Actions have started showing warnings on deprecated stuff:
Action versions were not really uniform; they've been updated to the latest version.
[This is the relevant GitHub blog entry mentioned](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/)
♥️ Thank you!
=> [:arrow_up:] Upgrade Github's own actions to v3

platform/feature-api/api/src/pod-api/api.ts, platform/feature-api/communication/src/remote-pod/async.ts, platform/feature-api/communication/src/remote-pod/remote.ts, platform/feature-api/communication/src/remote-pod/tests/node/async.test.ts
First hint is the fact that it's hidden in the documentation, but then their functions are not invoked anywhere or used in production, apparently. Its behavior is not documented, and its code has been sitting there for some time.
> I created this one, but still
I'll proceed cautiously here, since it might be used under some name we're not familiar with. So consider this a draft, although feedback is welcome. Anyway, this code was created by [this commit](https://github.com/polypoly-eu/polyPod/commit/2ef98b4b836cd4fae1d9b274bab1ca33598dffcc), which says `experimental`
WIP:
♥️ Thank you!
=> [:recycle:] {PROD4POD-1940} `polyLifecycle` is probably unused

feature-utils/poly-import/src/storage.js, feature-utils/poly-look/src/react-components/contexts/poly-import.jsx
While doing #1204 a bit of refactoring is needed; and I realized this return value is never used. Giving it its own PR since it's a change in API, and want it to be tested with the rest.
Also, some refactoring mainly eliminating `await` and `return` where they're not actually needed.
It contributes to cleaning the repository, and improve test coverage in `importer`; eliminating code that's not used will no doubt contribute to that.
♥️ Thank you!
=> [:coffin:] Refactoring return values

feature-utils/poly-import/utils/zipfile-mock.js, features/facebookImport/test/ministory/json-file-names-analysis.test.js, features/facebookImport/test/ministory/report-metadata.test.js, features/facebookImport/test/utils/data-creation.js
While doing #1204, the need to refactor mocks arose. It became a bit hefty for an already heavy PR, so it's better taken outside.
I'll leave it as draft for the time being, since some functions might be unneeded after this. Feedback welcome anyway.
♥️ Thank you!
=> [♻] Improve ZipFileMock constructor

platform/android/app/src/main/kotlin/coop/polypoly/polypod/settings/PrivacyPolicyFragment.kt
This is an alternative for #1227; that's a MVP for fixing the precise bug that was raised, but this one actually tries to mitigate the fact that specific privacy policies might not be present by presenting the English privacy policy.
There are probably better, DRYer alternatives.
=> [:bug:] {PROD4POD-1959} Adds a default privacy policy just in case there's not one

features/facebookImport/src/model/analyses/ministories/json-files-bubbles.js, features/facebookImport/test/ministory/json-files-bubbles-analysis.test.js
This code was the only one using the construction `zipFile.getContent`, which apparently disappeared a some point in time. It's been refactored to work as intended, getting the content of a single `ZipEntry`. Adds a tests which fails if the original content was used.
This was found while doing #1219, so it's a blocker for that one.
Deep tests have not really been performed; they're mainly sanity tests. Rendering tests are not checked either. Better mocks would probably be needed for better tests.
(Unrelated) coupling with `zipFile` has been eliminated from the function, since it's no longer needed. The function was returning a data structure which included it, not doing that does not seem to affect the outcome.
♥️ Thank you!
=> [♻] Add test for bubbles, refactor to avoid content error

features/test/package.json, features/test/src/test.ts
Most of the tests in the test feature were disabled because their
setup code was in the Android tests; CommunicationThroughPodApiWorks
specifically. That is now rectified.
=> PROD4POD-1930 - Enable skipped tests
