features/facebookImport/src/context/importer-context.jsx
features/facebookImport/src/locales/de/overview.json
features/facebookImport/src/locales/en/overview.json
features/facebookImport/src/views/overview/overview.css
features/facebookImport/src/views/overview/overview.jsx

This shows the list of imported files after the zip is imported. 
Right now the style and content are not 100% as in the designs.

Show file list after import

---

features/facebookImport/src/components/advertisingValueMiniStory/advertisingValueMiniStory.css
features/facebookImport/src/components/advertisingValueMiniStory/advertisingValueMiniStory.jsx
features/facebookImport/src/i18n.js
features/facebookImport/src/locales/de/miniStories/advertisingValue.json
features/facebookImport/src/locales/en/miniStories/advertisingValue.json
features/facebookImport/src/model/analyses/advertising-value-analysis.js
features/facebookImport/src/model/analysis.js

Add random ad interests analysis

Add advertising value analysis

---

features/facebookImport/src/components/offFacebookMiniStory/offFacebookMiniStory.css
features/facebookImport/src/components/offFacebookMiniStory/offFacebookMiniStory.jsx
features/facebookImport/src/i18n.js
features/facebookImport/src/locales/de/miniStories/offFacebookEvents.json
features/facebookImport/src/locales/en/miniStories/offFacebookEvents.json
features/facebookImport/src/model/analyses/off-facebook-events-analysis.js
features/facebookImport/src/styles.css

Fb knows what you did (off-facebook events) ministory.
Used the one we had for this.

Prod4 pod 803/fb knows

---

features/facebookImport/src/model/analysis.js

Remove the list of analyses that we want in the report from the list of ignored analyses.

Enable report analyses

---

core/communication/remote-pod/package.json

Should be enough. This should be also a temporary fix, we need to find out what's the problem here and why everything takes so long.

Increase timeout to fix failing tests

---

features/facebookImport/src/components/dialogs/polypolyDialog/polypolyDialog.css
features/facebookImport/src/components/dialogs/polypolyDialog/polypolyDialog.jsx
features/facebookImport/src/locales/de/overview.json
features/facebookImport/src/locales/en/overview.json
features/facebookImport/src/views/overview/overview.css
features/facebookImport/src/views/overview/overview.jsx

Add dialog before deleting file (reusable dialog) 
Style buttons in overview

Prod4 pod 810/new import dialog

---

features/facebookImport/src/components/importExplanationExpandable/importExplanationExpandable.jsx
features/facebookImport/src/context/importer-context.jsx
features/facebookImport/src/facebookImporter.jsx
features/facebookImport/src/model/storage.js

Change fakeStorage to initialize files with null

PROD4POD-829: Fix not going to overview with file loaded

---

features/facebookImport/rollup.config.js

Changes configuration to avoid them. This should not impact the generation and bundling of code otherwise.

[Fix] [PROD4POD-796]  Avoid warnings

---

android/app/src/main/kotlin/coop/polypoly/polypod/polyNav/PolyNav.kt
android/app/src/main/kotlin/coop/polypoly/polypod/polyOut/PolyOut.kt

Files are not actually removed without this fix

Fix removeFile on Android

---

ios/PolyPodApp/FeatureContainer/FeatureContainerView.swift
ios/PolyPodApp/PolyPod/FeatureView.swift
ios/PolyPodApp/PolyPod/de.lproj/Localizable.strings
ios/PolyPodApp/PolyPod/en.lproj/Localizable.strings

Fairly basic for now, but at least it won't leave the user in an
undefined state anymore.

PROD4POD-875 - Handle JS errors in iOS

---

ios/PolyPodApp/FeatureContainer/FilePicker.swift
ios/PolyPodApp/PodApi/PolyNav/PolyNav.swift
ios/PolyPodApp/PodApi/PolyOut/FS/PolyOut+FS.swift
ios/PolyPodApp/PodApi/PolyOut/PolyOut.swift

More specifically, I made the following changes:
1. Don't keep a copy of the ZIP file
2. Name directory with archive contents after the UUID
At first I tried to make these changes separately, but things were a bit
too intertwined for that.

PROD4POD-857 - Align iOS import logic with Android

---

features/facebookImport/src/components/dataViz/barChart.css
features/facebookImport/src/components/dataViz/barChart.jsx
features/facebookImport/src/locales/de/miniStories/messages.json
features/facebookImport/src/locales/en/miniStories/messages.json
features/facebookImport/src/model/analyses/ministories/messages-analysis.js

Just some colors and font changes.
Also added the max indicator

Improve message ministory

---

features/facebookImport/test/ministory/about-pictures-data-analysis.test.js

Basic tests for the About Pictures mini-story.

Test the About Pictures mini-story

---

features/facebookImport/src/model/analyses/ministories/messages-analysis.js
features/facebookImport/test/datasets/messages-data.js
features/facebookImport/test/importers/messages-importer.test.js
features/facebookImport/test/ministory/messages-analysis.test.js

Add basic tests for the Messages Summary mini-story. 
Simplifies also the activation condition of the analysis

Test the Messages Summary mini-story

---

features/facebookImport/src/model/importers/recently-viewed-ads-importer.js
features/facebookImport/test/datasets/ad-views-data.js

This chances the strings used for Videos as I used the ones in the wrong category before.
(Also RecentlyViewedAdsImporter is not an analysis.)

Fix for recently viewed strings

---

android/app/src/main/kotlin/coop/polypoly/polypod/FeatureContainer.kt
android/app/src/main/kotlin/coop/polypoly/polypod/Preferences.kt
android/app/src/main/kotlin/coop/polypoly/polypod/features/FeatureStorage.kt
android/app/src/main/kotlin/coop/polypoly/polypod/polyOut/PolyOut.kt

Following how it's implemented now on iOS.

Refactor active feature storage

---

features/facebookImport/src/model/analyses/ministories/activities-analysis.js
features/facebookImport/src/model/entities/facebook-account.js
features/facebookImport/src/model/importer.js
features/facebookImport/src/model/importers/comments-importer.js
features/facebookImport/test/datasets/comments-data.js
features/facebookImport/test/importers/comments-importer.test.js
features/facebookImport/test/utils/data-importing.js

This extract timestamp information for comments.

Partially import comments

---

features/facebookImport/package.json
features/facebookImport/src/model/analyses/report/inactive-cards-summary.js
features/facebookImport/src/model/analyses/report/ministories-status-analysis.js
features/facebookImport/src/model/analyses/utils/analysis-status.js
features/facebookImport/src/model/analyses/utils/performance-telemetry.js
features/facebookImport/src/model/analysis.js
features/facebookImport/test/config/env-setup.js
features/facebookImport/test/ministory/about-pictures-data-analysis.test.js
features/facebookImport/test/ministory/messages-analysis.test.js
features/facebookImport/test/ministory/missing-common-json-files.test.js
features/facebookImport/test/ministory/on-off-facebook-events-analysis.test.js
features/facebookImport/test/ministory/post-reactions-types-analysis.test.js
features/facebookImport/test/utils/analyses-execution.js

Introduce an analysis in the report that shows the running time for each mini-story.

Log performance for mini-stories

---

core/utils/poly-look/rollup.config.js
features/facebookImport/rollup.config.js
features/facebookImport/src/static/index.html

Add poly-look to html

---

features/polyExplorer/src/components/clusterStories/messengers/details.css
features/polyExplorer/src/components/clusterStories/messengers/details.jsx
features/polyExplorer/src/components/clusterStories/messengers/introduction.css
features/polyExplorer/src/components/clusterStories/messengers/introduction.jsx
features/polyExplorer/src/components/clusterStories/messengers/overview.jsx
features/polyExplorer/src/components/clusterStories/messengers/summary.css
features/polyExplorer/src/components/clusterStories/messengers/summary.jsx
features/polyExplorer/src/components/clusterStories/tab.css
features/polyExplorer/src/components/clusterStories/tab.jsx
features/polyExplorer/src/screens/stories/messengerStory.css
features/polyExplorer/src/screens/stories/messengerStory.jsx

Details section in Messenger Story in polyExplorer added: 
- PROD4POD-656
- PROD4POD-673: Not possible to add the concentric circles since there is missing data, but I have added the text.
Notes:
* Missing German translations.
* I had to work with unstyled fonts because I had to delete them (change not pushed) due to an error caused by this commit: https://github.com/polypoly-eu/polyPod/commit/827fca84d21bc9b5770098e0868f567749e51343.  I might need to adjust the CSS after that issue is solved.
* Also, renamed the fakeTab component.

PROD4POD-656/Details section in Messenger Story - polyExplorer

---

ios/PolyPodApp/PolyPod/AppDelegate.swift
ios/PolyPodApp/PolyPod/Info.plist
ios/PolyPodApp/PolyPod/SceneDelegate.swift

This doesn't seem to actually work yet - at least I couldn't produce a
notification in my tests yet.
_Showing_ the notification works, it's just the background task
scheduling that I haven't been able to get to work - or I haven't waited
long enough, given how iOS calls background tasks kinda arbitrarily.

PROD4POD-386 - Add push notifications on iOS

---

features/facebookImport/src/i18n.js
features/facebookImport/src/locales/de/miniStories/connectedAdvertisers.json
features/facebookImport/src/locales/de/overview.json
features/facebookImport/src/locales/en/miniStories/connectedAdvertisers.json
features/facebookImport/src/locales/en/overview.json
features/facebookImport/src/model/analyses/ministories/connected-advertisers-analysis.js
features/facebookImport/src/views/overview/overview.css
features/facebookImport/src/views/overview/overview.jsx

Prod4 pod 922/redesign overview screen

---

features/facebookImport/src/model/analysis.js

Move ConnectedAdvertisersAnalysis below the tech demos

Fix order or features

---

features/facebookImport/src/locales/de/miniStories/reactions.json
features/facebookImport/src/locales/en/miniStories/reactions.json
features/facebookImport/test/datasets/post-reactions-data.js
features/facebookImport/test/ministory/post-reactions-types-analysis.test.js

Fix issue with ANGER reaction

---

features/facebookImport/src/components/importExplanationExpandable/importExplanationExpandable.jsx
features/facebookImport/src/locales/de/import.json
features/facebookImport/src/locales/en/import.json
features/facebookImport/src/static/manifest.json

Adds the button to download direct the user to the page for downloading data

Add example data button

---

features/facebookImport/src/model/analysis.js

please check briefly if this is right way to remove the tech demos @RichardSto

PROD4POD-1080: remove all ministories marked as tech demo

---

android/app/src/main/kotlin/coop/polypoly/polypod/Authentication.kt
android/app/src/main/kotlin/coop/polypoly/polypod/FeatureCardAdapter.kt
android/app/src/main/kotlin/coop/polypoly/polypod/MainActivity.kt
android/app/src/main/kotlin/coop/polypoly/polypod/OnboardingActivity.kt
ios/PolyPodApp/PolyPod/Authentication.swift
ios/PolyPodApp/PolyPod/ContentView.swift
ios/PolyPodApp/PolyPod/OnboardingView.swift

The Android part is already done, the iOS part I'll finish quickly and then add another commit. But Android is already ready to be reviewed.

PROD4POD-1057/1061 - Change security flow

---

features/facebookImport/src/components/onOffFacebookMiniStory/onOffFacebookMiniStory.css
features/facebookImport/src/components/onOffFacebookMiniStory/onOffFacebookMiniStory.jsx
features/facebookImport/src/locales/de/miniStories/offFacebookEvents.json
features/facebookImport/src/locales/en/miniStories/offFacebookEvents.json
features/facebookImport/src/model/analyses/ministories/on-off-facebook-events-analysis.js
features/facebookImport/src/styles.css
features/facebookImport/src/views/explore/details.css

Restructure to how it was designed

Prod4 pod 1066/restructure off fb ministories

---

features/facebookImport/src/components/scrollableXGradient/scrollableXGradient.css
features/facebookImport/src/components/scrollableXGradient/scrollableXGradient.jsx
features/facebookImport/src/views/overview/overview.css
features/facebookImport/src/views/overview/overview.jsx

please check and merge @RichardSto . somehow couldn't change the className of the list-gradient :(

PROD4POD-1083: scale file name siz

---

core/utils/poly-look/package-lock.json
core/utils/poly-look/package.json

Mainly introduced through `@web` and `@open-wc`. Fixed through upgrading.

Upgrade to eliminate debug/mkdirp vulnerable versions

---

features/facebookImport/src/components/importExplanationExpandable/importExplanationExpandable.jsx

Just two little shiftings, please merge @RichardSto

PROD4POD-1085: shift Infoboxes as requested

---

features/facebookImport/src/components/activitiesMiniStory/activitiesMiniStory.css
features/facebookImport/src/components/activitiesMiniStory/activitiesMiniStory.jsx
features/facebookImport/src/components/activitiesMiniStory/datePicker.css
features/facebookImport/src/locales/de/miniStories/activities.json
features/facebookImport/src/locales/en/miniStories/activities.json

hi @RichardSto . Please have a look and merge, if you can approve :) thx

Prod4 pod 1126/add text to buttons

---

features/facebookImport/src/components/progressBar/progressBar.jsx

Just removing all logic here that was necessary to determine checkmarks

Prod4 pod 1132/remove numbers

---

features/facebookImport/src/components/activitiesMiniStory/activitiesMiniStory.jsx
features/facebookImport/src/locales/de/common.json
features/facebookImport/src/locales/en/common.json

This supersedes #520 by changing a literal to a string read from the i18n files. Maybe a better file could be used, but this is used in this file thus imported.

Changes title to i18n strings

---

features/demo/src/demo.js

Lint fixes to demo

---

build/index.js

Such as build or test. We might need it in the future to check what future optimizations buy us (if anything)

Adds timing information to heavy commands

---

android/app/src/main/res/layout/onboarding_slide.xml

Onboarding slide fonts corrected to match that of the iOS

PROD4POD-1075

---

features/facebookImport/src/model/analyses/report/unknown-json-files.js
features/facebookImport/src/model/analyses/report/unknown-top-level-folders-analysis.js
features/facebookImport/src/model/analysis.js
features/facebookImport/test/ministory/unknown-top-level-folders-analysis.test.js

There are various misspellings of the word "unknown" that bothered my
while investigating PROD4POD-1198 - though to be clear, those are
definitely not the cause of the issue.

PROD4POD-1198 - Fix typos

---

core/api/pod-api/src/default.ts

While checking out #560 I found a variable that was not used, and while I was at it, saw some repeated code that can be un-DRYed.

Some refactoring in pod-api

---

features/polyExplorer/src/components/clusterStories/receivingCompanies.jsx
features/polyExplorer/src/locales/de/stories/clusterMessengerStory.json
features/polyExplorer/src/locales/de/stories/common.json
features/polyExplorer/src/locales/en/stories/clusterMessengerStory.json
features/polyExplorer/src/locales/en/stories/common.json
features/polyExplorer/src/screens/stories/digitalGiantsStory.jsx
features/polyExplorer/src/screens/stories/messengerStory.jsx

Pretty basic for starters, but it shows the necessary information :)

PROD4POD-664 - Add basic Companies sections

---

core/utils/poly-look/src/visualisations/charts/bubble-charts/bubbleCluster/bubbleCluster.js
features/facebookImport/src/components/postReactionTypesMiniStory/postReactionTypesMiniStory.jsx
features/facebookImport/src/views/overview/overview.jsx
features/polyExplorer/src/components/clusterStories/receivingCompanies.css
features/polyExplorer/src/components/clusterStories/receivingCompanies.jsx

PROD4POD-664 - Finish Companies sections

---

ios/PolyPodApp/PodApi/PolyOut/FS/PolyOut+FS.swift

Unzipping is a heavy operation, execute on background thread to avoid blocking user interface.
Importing a large zip in Facebook Importer did freeze the app, making it unresponsive.

PROD4POD-1229: Execute unzipping on background thread

---

android/app/src/main/res/drawable/feature_card_border.xml
android/app/src/main/res/layout/feature_card.xml
android/app/src/main/res/values/colors.xml
android/app/src/main/res/values/dimensions.xml

- Removed feature card shadow
- Added border to feature card, matches iOS specs.

PROD4POD-1074: Android add border to feature card

---

core/utils/poly-look/src/visualisations/charts/line-charts/time-line-chart/timeLineChart.js
features/polyExplorer/src/components/clusterStories/messengerMauChart.css
features/polyExplorer/src/components/clusterStories/messengerMauChart.jsx

Improve line chart

---

features/polyExplorer/src/components/baseInfoScreen/baseInfoScreen.css
features/polyExplorer/src/components/baseInfoScreen/baseInfoScreen.jsx
features/polyExplorer/src/i18n.js
features/polyExplorer/src/locales/de/infoScreens/baseInfoScreen.json
features/polyExplorer/src/locales/en/infoScreens/baseInfoScreen.json

Reverts polypoly-eu/polyPod#610

Revert "PROD4POD-1240/Implement new HTRT screen basis design"

---

core/utils/poly-look/src/react-components/tabs/tabs.css

It's tiny but it annoyed me and I am not sure if someone has a veto in it? @RichardSto @mteresa-jimenez

Prod4Pod-1224: fix overflowing tab-title

---

.github/workflows/branch-name-policy.yml

It will fail if the branch name is incorrect.

Adds branch name policy test

---

.github/workflows/branch-name-policy.yml

Refine a bit the pattern used, as well as the message so that it makes a real suggestion on the name.

Finesse pattern

---

core/utils/poly-look/src/visualisations/charts/treeMap/treeMap.js
features/polyExplorer/package.json
features/polyExplorer/src/components/clusterStories/messengerTreeMap.jsx
features/polyExplorer/src/components/embeddedSankey/embeddedSankey.jsx
features/polyExplorer/src/data/companies.json
features/polyExplorer/src/data/global.json
features/polyExplorer/src/data/products.json

Updates the polypedia data (Fixing many issues eg. jurisdiction, data recipients missing etc. )

Prod4 pod 1210/update pp data

---

features/polyExplorer/src/components/entityList/entityList.css
features/polyExplorer/src/components/entityList/entityList.jsx

last merge was to quick, sorry @RichardSto this one should do it

P4P-1265: exchange inlinestyle against css class

---

features/polyExplorer/src/components/buttons/linkButton/linkButton.jsx
features/polyExplorer/src/context/explorer-context.jsx

Filter and search screen should be passed going back

Task/prod4 pod 1259/going back twice

---

.gitignore
debug.log
features/polyExplorer/src/components/clusterStories/overviewBarChart.jsx
features/polyExplorer/src/screens/stories/story-utils.js

the data for user count per company was not retrieved correctly previously. Now the function retrieving the latest user data is implemented instead.

Prod4 pod 1301 horizontal chart user data fix

---

features/polyExplorer/src/components/discoverCard/discoverCard.jsx

accessing the story is possible through the discover container rather than just the button

story accessible by clicking on image, text or button

---

core/utils/poly-look/src/css/themes.css
core/utils/poly-look/src/visualisations/charts/bar-charts/horizontalBarChart/horizontalBarChart.js
features/polyExplorer/src/components/clusterStories/overviewBarChart.css
features/polyExplorer/src/components/clusterStories/overviewBarChart.jsx

Changed the fonts for all svgs to be set to Jost medium by default. Made font size adjustments for horizontal-bar chart and some alignment fixes as well.

Prod4 pod 1288 horizontal bar chart font fix

---

.github/workflows/ios-test.yml
ios/Makefile

Mainly as a solution to [this discussion](https://github.com/polypoly-eu/polyPod/pull/613#discussion_r795456133) which preserves the single source of truth.

Upgrade iOS OS, XCode and destination + Xcode version as a Makefile target

---

features/polyExplorer/src/components/dataViz/purposesBarChart.jsx

- Label font-size
- Label/chips position
- Legend font-family
https://www.figma.com/file/xpeZC2jl9JIDqt1kiec5US/MAIN-Pod-prototype?node-id=8953%3A39780

PROD4POD-1311/ Fix Purposes label chips

---

features/polyExplorer/src/components/clusterStories/dataTypes.jsx
features/polyExplorer/src/screens/stories/story-utils.js

https://www.figma.com/file/xpeZC2jl9JIDqt1kiec5US/MAIN-Pod-prototype?node-id=9768%3A47247

PROD4POD-1322/Fix HTRT button position in Data Types

---

features/polyExplorer/src/components/dataViz/dataTypeBubbleAll.jsx

font size variability to fit in all bubbles fixed for data exploration.

Variable font size to be readable for all bubble sizes

---

features/polyExplorer/src/components/sourceInfoButton/sourceInfoButton.css
features/polyExplorer/src/screens/dataExploration/dataExploration.css

I think thats good enough. Still microshifting but can't figure out why. I don't think it's noticeable

Fix dataExploration CSS

---

features/polyExplorer/package.json
features/polyExplorer/src/data/companies.json
features/polyExplorer/src/data/highlights.js
features/polyExplorer/src/data/products.json

Still erroring but we know whats up.
amazon (us) doesnt have highlights yet
iMessage needs to have “IBM (US)” as dataRecipient
Meta platforms (Facebook (US)) needs UCL as dataRecipient
“TikTok Technology Limited (IE)” needs to have the correct ByteDance LTD ppid as dataRecipient
Adding Shopify to the dataRecipients of the WhatsApp product and WhatsApp LLC (US) company
Needs to be done

Fix/highlights 1.5 2

---

features/polyExplorer/src/locales/de/stories/clusterStoriesPreview.json
features/polyExplorer/src/locales/en/stories/clusterStoriesPreview.json

Fix "messenging"

---

features/polyExplorer/src/components/clusterStories/messengerMauChart.css

Just a typo in a CSS class. Couldn't find much else to pile here...

:bug: :pencil2:

---

.gitignore

Ignore files created by Android simulator

---

features/polyExplorer/src/components/buttons/linkButton/linkButton.jsx
features/polyExplorer/src/components/clusterStory/clusterStory.jsx
features/polyExplorer/src/components/screen/screen.jsx
features/polyExplorer/src/components/scrollingProgressTracker/scrollingProgressTracker.jsx
features/polyExplorer/src/context/explorer-context.jsx
features/polyExplorer/src/screens/stories/digitalGiantsStory.jsx
features/polyExplorer/src/screens/stories/messengerStory.jsx

This is a fix but a rather hacky one as we need to put it into all stories. We need to find a way in the future to save scrolling progress in a good way. We looked into it and couldn't find a solution better than this for now.

Add scrolling progress memory to stories

---

android/app/src/main/res/values-de/legal_strings.xml
android/app/src/main/res/values/legal_strings.xml
ios/PolyPodApp/PolyPod/de.lproj/Localizable.strings
ios/PolyPodApp/PolyPod/en.lproj/Localizable.strings

updating the imprint https://jira.polypoly.eu/browse/PROD4POD-1356

Jolly orc patch update management

---

ios/PolyPodApp/PolyPod/AppDelegate.swift
ios/PolyPodApp/PolyPod/SceneDelegate.swift

Disabled update notifications until we find a better solution to handle them

Disable update notifications

---

.github/workflows/rust_kernel_tests.yml
core/kernel/src/feature_manifest.rs

Essentially, minor reformatting after [this test failure](https://github.com/polypoly-eu/polyPod/runs/5272763973?check_suite_focus=true)
Also change a bit the :memo: on the GitHub action.

Fix kernel linting issues

---

.github/workflows/js-and-android-test.yml

We need to launch tests also in this case

Small correction to workflows so that feature-utils are also tested

---

feature-utils/poly-look/package-lock.json

Trying to find a way to eliminate a deprecated upstream dep, but no joy.

Update package-lock.json for poly-look

---

platform/feature-api/api/rdf-spec/package-lock.json
platform/feature-api/api/rdf-spec/package.json
platform/feature-api/api/rdf-spec/src/tests/_factories.ts

And while I'm at it, also upgrade some of the tools used.

Fix maintenance TODOs in rdf-spec

---

.github/workflows/ios-test.yml

Complementary to #730, on the other side.

Refine iOS workflow

---

platform/android/app/src/main/kotlin/coop/polypoly/polypod/PodApi.kt
platform/android/app/src/main/kotlin/coop/polypoly/polypod/ZipTools.kt
platform/android/app/src/main/kotlin/coop/polypoly/polypod/info/Info.kt
platform/android/app/src/main/kotlin/coop/polypoly/polypod/network/Network.kt
platform/android/app/src/main/kotlin/coop/polypoly/polypod/polyOut/PolyOut.kt

Mainly addresses little warnings that were showing up in builds, and also popped up in Android Studio. Helping myself familiarize with the Kotlin code source, too.

[Task] address kotlin warnings

---

.github/workflows/ios-test.yml
.github/workflows/upload_app_store.yml
platform/ios/Makefile
platform/ios/PolyPodApp/PolyPodTests/UpdateNotificationTest.swift

It's a bit error prone to pipe _all_ output from the Makefile through
xcpretty, so I moved the call to the Makefile.

PROD4POD-1426 - Invoke xcpretty from Makefile

---

.editorconfig
features/test/src/test.ts
platform/feature-api/api/pod-api/.editorconfig
platform/feature-api/api/rdf-convert/.editorconfig
platform/feature-api/api/rdf-spec/.editorconfig
platform/feature-api/api/rdf/.editorconfig
platform/feature-api/communication/bubblewrap/.editorconfig
platform/feature-api/communication/port-authority/.editorconfig
platform/feature-api/communication/postoffice/.editorconfig
platform/feature-api/communication/remote-pod/.editorconfig
platform/feature-api/communication/remote-pod/src/remote.ts
platform/podjs/.editorconfig

Re-applying [reverted PR ](https://github.com/polypoly-eu/polyPod/commit/07c975ca02dd514b1d110570e7e15c1eef15a392)
after correcting the `root = true` on child editorconfig files.
Thanks for the catch @fhd  👁️ 🦅

config: change global `max_line_length` to 80 - [PROD4POD-1455]

---

platform/android/app/src/main/kotlin/coop/polypoly/polypod/endpoint/Endpoint.kt
platform/android/app/src/main/kotlin/coop/polypoly/polypod/network/Network.kt
platform/ios/PolyPodApp/PodApi/Endpoint/Endpoint.swift
platform/ios/PolyPodApp/PodApi/Network/Network.swift
platform/ios/PolyPodApp/PodApi/PodApiError.swift
platform/ios/PolyPodApp/PolyPodTests/Info.plist
platform/podjs/src/browserPod.ts
platform/utils/endpoints-generator/endpoints.js
platform/utils/endpoints-generator/index.js

Erroring out if url is not of protocol type https

Prod4 pod 1436 only allowing https endpoint urls

---

features/test/src/test.ts
platform/feature-api/communication/remote-pod/src/remote.ts

Eliminate warnings that were showing up in builds (and replicated in PRs)

Fix ⚠ resulting from fetch spec elimination

---

dev-utils/visualise-ui-hierarchy/.gitignore
dev-utils/visualise-ui-hierarchy/Makefile
dev-utils/visualise-ui-hierarchy/README.md
dev-utils/visualise-ui-hierarchy/tree2dot

It's a bit hacky, but I believe worth merging - as long as it's tucked away in _dev-utils_, it shouldn't give us any trouble.

Add basic visualisation tool

---

build/index.js

Fix build.js problems

---

platform/feature-api/communication/rollup.config.js

Clarifying those are built for a specific window context.

Fix rollup warnings

---

features/polyExplorer/cypress/helpers/index.js
features/polyExplorer/cypress/helpers/indexed-db.js
features/polyExplorer/cypress/integration/dataStories_spec.js
platform/podjs/package-lock.json
platform/podjs/package.json
platform/podjs/src/browserPod.ts

For context, see https://jira.polypoly.eu/browse/PROD4POD-1496.
If there is an established way to reference Jira issues from pull request and commit messages please let me know?
Also I could use some guidance on how to test this change?

Migrate pod.js from localStorage to IndexedDB

---

features/facebookImport/src/views/overview/overview.jsx

Import INITIAL_HISTORY_STATE and use it when rerouting

Fix the scrolling error by adding state on rerouting

---

features/facebookImport/src/model/analysis.js
features/facebookImport/src/views/overview/overview.jsx
features/facebookImport/test/utils/analyses-execution.js

SubAnalyses shouldn't be used any longer

Rename to specificAnalyses

---

features/google/src/views/explore/explore.css
features/google/src/views/explore/explore.jsx
features/google/src/views/ministories/activitiesByProduct.jsx
features/google/src/views/ministories/dataImportingStatus.jsx
features/google/src/views/ministories/dataStructure.jsx
features/google/src/views/ministories/groupedActivityTypes.jsx
features/google/src/views/ministories/placeVisits.jsx

Also make it use the title property

Add tech demo label back

---

features/google/src/model/importers/activities-importer.js
features/google/src/model/importers/semantic-locations-importer.js
features/google/src/views/ministories/story.jsx
platform/ios/PolyPodApp/PodApi/PolyOut/FS/PolyOut+FS.swift

Doing two things here:
Making it so when analyses have no data they are actually not shown (through missing `_` active was always true).
Replace `"%20"` with `" "` to fix paths in ios

Fix non linux path bug

---

features/google/src/google.jsx
features/google/src/views/explore/explore.css
features/google/src/views/explore/explore.jsx
features/google/src/views/report/details.css
features/google/src/views/report/details.jsx
features/google/src/views/report/report.css
features/google/src/views/report/report.jsx
features/google/src/views/report/reportWrapper.jsx

Added a reporting views and report for DataImporting status is working. Endpoint that the reports are sent to is identical to FbImporter.

Prod4 pod 1567 google reports

---

.github/workflows/codeql-analysis.yml
platform/android/app/build.gradle

Also added assertion to fail the build if the file is missing

Fix android boostrap.js path

---

feature-utils/poly-look/src/css/design-tokens.css
feature-utils/poly-look/src/css/index.js
feature-utils/poly-look/src/css/layout.css
feature-utils/poly-look/src/react-components/list.css
feature-utils/poly-look/src/react-components/overlays/screen.css
features/google/src/views/explore/explore.css

GDU grid distance unit is a 4px base unit

Add design tokens and revise css

---

feature-utils/poly-look/src/react-components/overlays/screen.css
features/facebookImport/src/views/explore/explore.css
features/facebookImport/src/views/explore/explore.jsx
features/google/src/components/sourceInfoButton/sourceInfoButton.css
features/google/src/views/explore/explore.css

Using screen to fix Fbimport styling

Fix the screen styling on fbImport

---

platform/ios/PolyPodApp/PolyPod/Info.plist

Remove key that disables Apple Transport Security

PROD4POD-1575 Reenable ATS

---

features/facebookImport/src/components/activitiesMiniStory/activitiesMiniStory.css
features/facebookImport/src/components/activitiesMiniStory/datePicker.css
features/facebookImport/src/components/advertisingValueMiniStory/advertisingValueMiniStory.css
features/facebookImport/src/components/chartButtons/chartButtons.css
features/facebookImport/src/components/dataViz/barChart.css
features/facebookImport/src/components/dataViz/barChartHorizontal.css
features/facebookImport/src/components/dialogs/polypolyDialog/polypolyDialog.css
features/facebookImport/src/components/importExplanationExpandable/importExplanationExpandable.css
features/facebookImport/src/components/listOfDetails/listOfDetails.css
features/facebookImport/src/components/onOffFacebookMiniStory/onOffFacebookMiniStory.css
features/facebookImport/src/components/scrollableXGradient/scrollableXGradient.css
features/facebookImport/src/components/tabs/tabs.css
features/facebookImport/src/views/explore/details.css
features/facebookImport/src/views/explore/explore.css
features/facebookImport/src/views/overview/overview.css
features/facebookImport/src/views/report/details.css
features/facebookImport/src/views/report/report.css
features/google/src/components/activitiesOverTimeStory/activitiesOverTimeStory.css
features/google/src/components/activitiesOverTimeStory/datePicker.css
features/google/src/components/importExplanationExpandable/importExplanationExpandable.css
features/google/src/views/explore/explore.css

Implement them in the `google` and `facebook` features.

PROD4POD-1598 Implement font-size variables from poly-look

---

platform/ios/PolyPodApp/PodApi/PolyOut/FS/PolyOut+FS.swift

Reverts polypoly-eu/polyPod#917

Revert "Fix ios bug"

---

platform/android/app/src/main/kotlin/coop/polypoly/polypod/polyOut/PolyOut.kt
platform/ios/PolyPodApp/PodApi/PolyOut/FS/PolyOut+FS.swift

Same as https://github.com/polypoly-eu/polyPod/pull/917 but merge into release

Fix breaking app read dir

---

features/google/src/model/importers/access-log-importer.js
features/google/src/model/importers/activities-importer-html.js
features/google/src/model/importers/activities-importer-json.js

Importers not importing data correctly lead to wrong analysis ministories

fix google importer problems 

---

dev-utils/visualise-ui-hierarchy/README.md

Simply adding available targets.

Slightly improve description of the visual component hierarchy

---

features/facebookImport/src/views/report/report.jsx
features/google/src/views/report/report.jsx

Seems to be a typo in the used endpoint

Fix endpoint reports

---

features/facebookImport/rollup.config.mjs
platform/utils/endpoints-generator/endpoints.js
platform/utils/endpoints-generator/index.js

Adding google endpoint.
The fbImport feature should not have these replaces any longer

Add google endpoint

---

features/facebookImport/src/views/report/report.jsx
features/google/src/views/report/report.jsx
platform/utils/endpoints-generator/endpoints.js

Adapt endpoint calls to new infrastructure

Fix endpoints importers

---

features/google/src/components/activitiesOverTimeStory/activitiesOverTimeStory.jsx
features/google/src/locales/de/common.json
features/google/src/locales/de/overview.json
features/google/src/locales/de/story/dataStructure.json
features/google/src/locales/en/common.json
features/google/src/locales/en/overview.json
features/google/src/locales/en/story/dataStructure.json
features/google/src/views/overview/overview.jsx

Fixes to some UI issues mentioned in slack

Fix svens remarks

---

platform/feature-api/api/pod-api/src/api.ts

:memo: A few grammar fixes found while doing other stuff. Not really important.

[🐛] Minor grammar corrections here and there

---

platform/ios/PolyPodApp/PolyPod/en.lproj/Localizable.strings

The verb is "log in" https://grammarist.com/spelling/log-in-login/

[Grammar bug] "login" is only a substantive or adjective

---

README.md

With a positive result. Kudos!

Changing status of trademarks after challenges

---

platform/android/app/build.gradle
platform/android/app/src/main/AndroidManifest.xml
platform/android/app/src/main/kotlin/coop/polypoly/polypod/FeatureCardAdapter.kt
platform/android/app/src/main/kotlin/coop/polypoly/polypod/settings/MainFragment.kt
platform/android/app/src/main/kotlin/coop/polypoly/polypod/settings/SettingsActivity.kt
platform/android/build.gradle
platform/android/gradle/wrapper/gradle-wrapper.properties
platform/android/polyOut/build.gradle

Preparing the project for the new home screen (Jetpack Compose).
Updated: 
1. Gradle version
2. Kotlin version 
3. SDK version
4. Dependencies 
Fixed build warnings

Android gradle upgrades

---

features/google/src/model/google-account.js

the new importers were not added into the dataAccount correctly and were not added to  dataGroups.

add to dataGroups

---

features/google/src/components/importExplanationExpandable/importExplanationExpandable.jsx
features/google/src/views/explore/explore.jsx

click on the file in the list and remove the file from the selected files

Prod4 pod 1637 delete previously selected files

---

features/google/src/locales/de/overview.json
features/google/src/locales/en/overview.json
features/google/src/views/overview/overview.jsx

Uses current locale, which is independent of the translation locale. Please check the Spanish date format in the screenshot.

[Fix] {PROD4POD-1641} Show imported date

---

features/google/src/model/importers/access-log-importer.js
features/google/src/model/importers/activities-importer-html.js
features/google/src/model/importers/activities-importer-json.js
features/google/src/model/importers/semantic-locations-importer.js

change from getEntries to relevantZipEntries in order to filter out files that are not needed

Prod4 pod 1659 read relevant entries

---

features/google/src/context/google-context.jsx
features/google/src/locales/de/navbarTitles.json
features/google/src/locales/en/navbarTitles.json

Try to add the navbar titles to the translation strings, and also add title changes to the effect... Somehow I can't manage it to work. Leaving it in draft, since I guess we'll halfway there.

[Fix] {PROD4POD-1646} Fix navbar titles

---

.github/workflows/js-and-android-test.yml

Using the new hash here. It fixes some security advisories that were showing up in snyk. No functionality has changed.

Security update for GitHub action dorny/path-filters

---

feature-utils/poly-look/src/css/layout.css
features/facebookImport/src/views/explore/details.css
features/facebookImport/src/views/explore/details.jsx
features/google/src/views/explore/details.jsx

Add title and make fb have the same logic

Add the title and stylings

---

feature-utils/poly-look/src/react-components/overlays/sideSwiper.jsx
features/google/src/popUps/info/base.jsx

Just a small change requested by the Sculptors. Also, since all of our HTRT screens should look the same, I figured it's easier to just set the default value and not override it.

fix - prod4pod-1702 decrease SideSwiper default leftDistance

---

platform/android/build.gradle
platform/android/gradle/wrapper/gradle-wrapper.properties

Update Gradle version to 7.3.3

Upgrade Gradle version

---

platform/feature-api/api/package-lock.json
platform/feature-api/api/package.json

This was causing problems down the line.

Eliminate unneeded modules in merged code

---

features/bundle/package.json
platform/ios/PolyPodApp/PolyPod/HomeScreenView.swift

Title fixes according to feedback gathered. Tests were only for Android, but the iOS text seems to be wrong too.

Know how → Data Know-How

---

features/polyTalkPreview/src/index.jsx
features/polyTalkPreview/src/static/manifest.json
features/polyTalkPreview/src/styles.css

This PR adds the separator and sets the right color for the navbar.
~It's still in draft because I can't verify the changes on a device or emulator, so if somebody can help me with that it would be awesome.~

fix: prod4pod-1728,1733 - small navbar fixes

---

dev-utils/poly-cli/src/static/templates/locales/preview.json
dev-utils/poly-cli/src/static/templates/preview/content.json
dev-utils/poly-cli/src/static/templates/preview/styles.css

Additional improvements to the task generator, mainly mentioned in Slack.
:sunglasses: : I'm bored of Lorem Ipsum

Task generator improvements redux

---

dev-utils/poly-cli/src/static/templates/preview/styles.css
features/amazonDataImporterPreview/src/styles.css
features/companyDataCleanerPreview/src/styles.css
features/cooperativeMembershipPreview/src/styles.css
features/featureStorePreview/src/styles.css
features/gdprDataImporterPreview/src/styles.css
features/netflixDataImporterPreview/src/styles.css
features/polyTalkPreview/src/styles.css
features/polypediaPreview/src/styles.css
features/polypolyMembershipPreview/src/styles.css

This PR updates the styles in the cli and then makes sure that all the preview features have the exact same style.css.

Preview features: more font fixes

---

feature-utils/poly-look/src/react-components/overlays/sideSwiper.jsx

The reason for the maybe is that I've only been able to reproduce this bug 2 times. 
Based on the state of the component I'm assuming that this is the right fix, although I can't guarantee, but at least it doesn't break anything.

fix: prod4pod-1739 - maybe fix htrt getting stuck

---

features/polyTalkPreview/src/styles.css

Basically change some fonts that were incorrect in rendering. Changed only in one preview, can be extended to others if it's OK

[🐛] Font cutoff (and other) issues

---

dev-utils/poly-cli/src/static/templates/locales/de/progressInfo.json
dev-utils/poly-cli/src/static/templates/locales/en/progressInfo.json
features/amazonDataImporterPreview/src/locales/de/progressInfo.json
features/amazonDataImporterPreview/src/locales/en/progressInfo.json
features/companyDataCleanerPreview/src/locales/de/progressInfo.json
features/companyDataCleanerPreview/src/locales/en/progressInfo.json
features/cooperativeMembershipPreview/src/locales/de/progressInfo.json
features/cooperativeMembershipPreview/src/locales/en/progressInfo.json
features/featureStorePreview/src/locales/de/progressInfo.json
features/featureStorePreview/src/locales/en/progressInfo.json
features/gdprDataImporterPreview/src/locales/de/progressInfo.json
features/gdprDataImporterPreview/src/locales/en/progressInfo.json
features/netflixDataImporterPreview/src/locales/de/progressInfo.json
features/netflixDataImporterPreview/src/locales/en/progressInfo.json
features/polyTalkPreview/src/locales/de/progressInfo.json
features/polyTalkPreview/src/locales/en/progressInfo.json
features/polypediaPreview/src/locales/de/progressInfo.json
features/polypediaPreview/src/locales/en/progressInfo.json
features/polypolyMembershipPreview/src/locales/de/progressInfo.json
features/polypolyMembershipPreview/src/locales/en/progressInfo.json

Removed emoji from the HTRT screen. 
Content change

PROD4POD-1750-Remove-Emoji-from-HTRT

---

features/bundle/package.json

fix "your data" features order on home screen - PROD4POD-1747

---

features/polypediaPreview/src/styles.css

[Fix] {PROD4POD-1763} Polypedia footer font weight

---

platform/android/app/build.gradle

Might be already set by default for all I know, but still

[🐛] {PROD4POD-1755} Debuggable set to false

---

feature-utils/poly-import/package-lock.json
feature-utils/poly-import/package.json
feature-utils/poly-import/rollup.config.js

This was extracted from #977 since it's actually unrelated.

[⚰] Unused deps and config in poly-import

---

feature-utils/poly-look/src/react-components/banners/banner.css

[♻] {PROD4POD-1694} Banner UI improvements

---

platform/podjs/src/browserPod.ts

Broke in my feature branch fixing it here. Ts likes it better this way
The breaking

Fix missing parenthesis

---

features/google/src/model/importers/access-log-importer.js
features/google/src/model/importers/activities-importer-html.js
features/google/src/model/importers/activities-importer-json.js
features/google/src/model/importers/base-activities-importer.js
platform/ios/PolyPodApp/PodApi/PolyOut/FS/PolyOut+FS.swift
platform/ios/PolyPodApp/PolyPod/ContentView.swift

Added some logs with the google importer metadata. This will be used to asses if the problem with missing data is located in importer code, or the UI level.

PROD4POD-1841: Log google importer metadata

---

features/facebookImport/src/views/import/import.jsx
features/google/src/components/importExplanationExpandable/importExplanationExpandable.jsx

-> Does not fix the bug discussed here: https://jira.polypoly.eu/browse/PROD4POD-1841

Fix some bug with import maybe

---

platform/utils/endpoints-generator/endpoints.js

https://jira.polypoly.eu/browse/IN-374

IN-374 Updates to improved secret's name.

---

feature-utils/poly-sparql/.gitignore
feature-utils/poly-sparql/jest.config.js
feature-utils/poly-sparql/package-lock.json
feature-utils/poly-sparql/package.json
feature-utils/poly-sparql/rollup.config.js
feature-utils/poly-sparql/src/index.js
feature-utils/poly-sparql/src/namespaces.js
feature-utils/poly-sparql/src/query-templates.js
feature-utils/poly-sparql/src/triple-generation.js
feature-utils/poly-sparql/tests/triple-generation.test.ts

See #1100 
For testing purposes, we had a lot of other code in it, while the changes only regard _feature-utils/poly-sparql_

SPARQL Generator Nr. 2 #1100

---

platform/android/app/src/main/kotlin/coop/polypoly/polypod/features/FeatureStorage.kt
platform/core/PolyPodCoreAndroid/core/src/main/kotlin/coop/polypoly/core/Core.kt
platform/core/PolyPodCoreAndroid/core/src/main/kotlin/coop/polypoly/core/JniApi.kt
platform/core/PolyPodCoreSwift/Sources/PolyPodCoreSwift/Core.swift
platform/core/crates/feature_categories/src/lib.rs
platform/core/ffi/src/c_interface.rs
platform/core/ffi/src/java_interface.rs
platform/core/lib/src/lib.rs
platform/ios/PolyPodApp/Extensions/UserDefaultsExtensions.swift
platform/ios/PolyPodApp/Features/FeatureStorage.swift
platform/ios/PolyPodApp/PolyPod.xcodeproj/project.pbxproj
platform/ios/PolyPodApp/PolyPod/HomeScreenView.swift
platform/ios/PolyPodApp/PolyPodUITests/FeatureTest.swift
platform/ios/PolyPodApp/PolyPodUITests/XCUIApplicationExtensions.swift

With this, the test feature's tests are executed along with the other
iOS UI tests.
I had to make some changes to platform core, which lead to some
changes in the Android code, but I intend to tackle the Android part
(PROD4POD-1721) separately.

Run the test feature in iOS CI

---

features/facebookImport/src/model/importers/utils/importer-util.js

[`escape()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/escape) is deprecated and should not be used anymore 
Adding a by-character decode to actually fix the decoding

One escape too much it seems

---

features/google/src/locales/en/import.json

fix small typo in import button
before:
♥️ Thank you!

fix typo in import button

---

features/facebookImport/test/formatTime.test.js

Not in user-facing messages, but still... 
♥️ Thank you!

Just some typos

---

platform/android/app/build.gradle
platform/android/app/src/androidTest/kotlin/coop/polypoly/polypod/FeatureSmokeTest.kt
platform/android/app/src/main/kotlin/coop/polypoly/polypod/FeatureContainer.kt
platform/android/app/src/main/kotlin/coop/polypoly/polypod/homescreen/HomeScreenFragment.kt
platform/android/app/src/main/kotlin/coop/polypoly/polypod/homescreen/HomeScreenTiles.kt

Opens all features and checks if an error dialog comes up.

Android open features smoke test

---

.github/workflows/ios-test.yml
platform/ios/Makefile

Several Xcode version where released in the meantime. Update to the latest(which also requires to update macOS version)

Update to Xcode 13.4.1

---

platform/android/app/src/main/java/coop/polypoly/polypod/PodUnlockActivity.kt

Disable back navigation from UnlockPolyPod screen.

[PROD4POD-1871] - UnlockPolyPod disable back navigation

---

features/google/package.json
features/google/test/google-account.test.js

Set up unit tests for Google importer. The scope of this PR does not include a whole set of tests, just a simple, sanity test and the setup of the unit test framework.
Arguably, "fixes" it since there are *some* tests (as opposed to none)

✅ Set up tests for the google importer

---

platform/android/app/src/main/kotlin/coop/polypoly/polypod/FeatureContainer.kt

Turns out the PostOfficeMessageCallback instance was being garbage
collected at the end of initPostOffice - at least on my device.

Fix communication breakdown

---

feature-utils/poly-import/src/entities/data-account.js
features/facebookImport/src/model/importer.js
features/facebookImport/src/model/importers/personal-data-importer.js
features/facebookImport/test/importers/personal-data-importer.test.js
features/facebookImport/test/utils/data-importing.js

Replacing name importer with personal data importer and import name in the format schema.org has defined in rdf.

Add personal data importer

---

platform/android/app/src/main/kotlin/coop/polypoly/polypod/FeatureContainer.kt

This is suggested [here](https://stackoverflow.com/questions/23844667/how-do-i-detect-if-i-am-in-release-or-debug-mode) and it makes sense; only I'm not totally sure this flag is changed in production (probably yes)
♥️ Thank you!

[🐛] {PROD2POD-1752} Use best practices for enabling debug or not

---

platform/ios/Makefile

Xcode 14 and iOS 16 is released, update to latest.

Update to Xcode 14

---

platform/android/app/src/debug/res/xml/network_security_config.xml
platform/android/app/src/main/res/xml/network_security_config.xml

As advised here: https://stackoverflow.com/questions/15242600/debug-and-production-resources
Some support for compiling in debug mode might be needed, although it's probably the default
♥️ Thank you!

[🐛] {PROD2POD-1756} Separate debug and release configurations

---

features/google/src/model/importers/activities-importer-html.js
features/google/src/model/importers/activities-importer-json.js

Remove google activity bugchaser logs

---

features/polypolyMembership/src/context/membership-context.jsx
features/polypolyMembership/src/locales/de/navbarTitles.json
features/polypolyMembership/src/locales/en/navbarTitles.json
features/polypolyMembership/src/polypolyMembership.jsx
features/polypolyMembership/src/static/manifest.json

Add navigation in the app: 
- It's possible to go back using the "Escape button"
- Nav bar titles update when going to a different screen
- Fix nav bar styles
Find screen titles here: https://wiki.polypoly.eu/pages/viewpage.action?spaceKey=MEM&title=Content+for+GDPR+Helper+feature
*German translation missing.

PROD4POD-1833 Create navigation for the Membership/GDPR Helper feature

---

feature-utils/poly-look/package.json
features/bundle/package-lock.json
features/google/package.json
features/lexicon/package-lock.json
features/polyExplorer/package.json

Eliminate remaining vulnerable versions
`d3` moved back to "production" dependencies
♥️ Thank you!

[🐛] d3-color vulnerabilities fixed

---

platform/feature-api/communication/rollup.config.js

Fixing warnings is a general hygiene measure even if, as in this case, it's (mostly) not in our own code. We have also factored out common code for good  DRY measure
♥️ Thank you!

[♻] Fix remaining rollup warnings about circular deps

---

features/facebookImport/src/components/messagesMiniStory/messagesMiniStory.jsx

`l12n` has been part of `silly-i18n` for some time, but it's not been used. This is just a small refactoring to show its possibilities, and eliminate some non-l12 formatting
♥️ Thank you!

[♻] Introduce usage of l12n

---

platform/android/app/src/main/kotlin/coop/polypoly/polypod/MainActivity.kt
platform/android/app/src/main/res/xml/network_security_config.xml

Should solve build issue here: https://github.com/polypoly-eu/polyPod-deploy/actions/runs/3243529318/jobs/5320666135

Fix android gradle

---

features/facebookImport/package.json

Add coverage testing. Just to be aware of what we're missing.

[:white_check_mark:] Add coverage

---

.github/pull_request_template.md

Polishing a bit the PR template by erasing the _disturbing_ 'description' title and providing: 
- a brief description of the PR with a link to the 'closed' JIRA ticket (if any)
- the main implementation description (if required), with a tag to the co-pair (if applied)
- a section for 'testing' the pushed changes (if found helpful)
- a table for screenshots (to help thevisualisation of the front-end tasks)
any proposals are more than welcome :) 
Final looks in gitHub 🎨 :

Polish pull-request template

---

platform/ios/README.md

Follows my own problems trying to build the app
But is consistent with documenting and making the repository presentable.

[📝] Clarify build instructions
